package com.brightedu.dao.edu;

import com.brightedu.model.edu.AgentType;
import com.brightedu.model.edu.AgentTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface AgentTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.agent_type
     *
     * @mbggenerated Fri Feb 10 17:49:12 CST 2012
     */
    int countByExample(AgentTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.agent_type
     *
     * @mbggenerated Fri Feb 10 17:49:12 CST 2012
     */
    int deleteByExample(AgentTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.agent_type
     *
     * @mbggenerated Fri Feb 10 17:49:12 CST 2012
     */
    @Delete({
        "delete from edu.agent_type",
        "where agent_type_id = #{agent_type_id,jdbcType=NUMERIC}"
    })
    int deleteByPrimaryKey(Integer agent_type_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.agent_type
     *
     * @mbggenerated Fri Feb 10 17:49:12 CST 2012
     */
    @Insert({
        "insert into edu.agent_type (agent_type_id, agent_type_name, ",
        "is_return)",
        "values (#{agent_type_id,jdbcType=NUMERIC}, #{agent_type_name,jdbcType=VARCHAR}, ",
        "#{is_return,jdbcType=BIT})"
    })
    int insert(AgentType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.agent_type
     *
     * @mbggenerated Fri Feb 10 17:49:12 CST 2012
     */
    int insertSelective(AgentType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.agent_type
     *
     * @mbggenerated Fri Feb 10 17:49:12 CST 2012
     */
    List<AgentType> selectByExample(AgentTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.agent_type
     *
     * @mbggenerated Fri Feb 10 17:49:12 CST 2012
     */
    @Select({
        "select",
        "agent_type_id, agent_type_name, is_return",
        "from edu.agent_type",
        "where agent_type_id = #{agent_type_id,jdbcType=NUMERIC}"
    })
    @ResultMap("BaseResultMap")
    AgentType selectByPrimaryKey(Integer agent_type_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.agent_type
     *
     * @mbggenerated Fri Feb 10 17:49:12 CST 2012
     */
    int updateByExampleSelective(@Param("record") AgentType record, @Param("example") AgentTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.agent_type
     *
     * @mbggenerated Fri Feb 10 17:49:12 CST 2012
     */
    int updateByExample(@Param("record") AgentType record, @Param("example") AgentTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.agent_type
     *
     * @mbggenerated Fri Feb 10 17:49:12 CST 2012
     */
    int updateByPrimaryKeySelective(AgentType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.agent_type
     *
     * @mbggenerated Fri Feb 10 17:49:12 CST 2012
     */
    @Update({
        "update edu.agent_type",
        "set agent_type_name = #{agent_type_name,jdbcType=VARCHAR},",
          "is_return = #{is_return,jdbcType=BIT}",
        "where agent_type_id = #{agent_type_id,jdbcType=NUMERIC}"
    })
    int updateByPrimaryKey(AgentType record);
}