package com.brightedu.dao.edu;

import com.brightedu.model.edu.AgentReturn;
import com.brightedu.model.edu.AgentReturnExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import com.brightedu.model.edu.AgentReturnKey;

public interface AgentReturnMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table edu.agent_return
	 * @mbggenerated  Thu Feb 09 18:11:26 CST 2012
	 */
	int countByExample(AgentReturnExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table edu.agent_return
	 * @mbggenerated  Thu Feb 09 18:11:26 CST 2012
	 */
	int deleteByExample(AgentReturnExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table edu.agent_return
	 * @mbggenerated  Thu Feb 09 18:11:26 CST 2012
	 */
	@Delete({ "delete from edu.agent_return",
			"where agent_id = #{agent_id,jdbcType=NUMERIC}",
			"and ag_return_type_id = #{ag_return_type_id,jdbcType=NUMERIC}",
			"and batch_id = #{batch_id,jdbcType=NUMERIC}" })
	int deleteByPrimaryKey(AgentReturnKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table edu.agent_return
	 * @mbggenerated  Thu Feb 09 18:11:26 CST 2012
	 */
	@Insert({
			"insert into edu.agent_return (agent_id, ag_return_type_id, ",
			"batch_id)",
			"values (#{agent_id,jdbcType=NUMERIC}, #{ag_return_type_id,jdbcType=NUMERIC}, ",
			"#{batch_id,jdbcType=NUMERIC})" })
	int insert(AgentReturnKey record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table edu.agent_return
	 * @mbggenerated  Thu Feb 09 18:11:26 CST 2012
	 */
	int insertSelective(AgentReturnKey record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table edu.agent_return
	 * @mbggenerated  Thu Feb 09 18:11:26 CST 2012
	 */
	List<AgentReturnKey> selectByExample(AgentReturnExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table edu.agent_return
	 * @mbggenerated  Thu Feb 09 18:11:26 CST 2012
	 */
	int updateByExampleSelective(@Param("record") AgentReturnKey record,
			@Param("example") AgentReturnExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table edu.agent_return
	 * @mbggenerated  Thu Feb 09 18:11:26 CST 2012
	 */
	int updateByExample(@Param("record") AgentReturnKey record,
			@Param("example") AgentReturnExample example);
}