package com.brightedu.dao.edu;

import com.brightedu.model.edu.AgreeReturn;
import com.brightedu.model.edu.AgreeReturnExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface AgreeReturnMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.agree_return
     *
     * @mbggenerated Tue Jan 31 12:29:48 CST 2012
     */
    int countByExample(AgreeReturnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.agree_return
     *
     * @mbggenerated Tue Jan 31 12:29:48 CST 2012
     */
    int deleteByExample(AgreeReturnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.agree_return
     *
     * @mbggenerated Tue Jan 31 12:29:48 CST 2012
     */
    @Delete({
        "delete from edu.agree_return",
        "where agree_return_id = #{agree_return_id,jdbcType=NUMERIC}"
    })
    int deleteByPrimaryKey(Integer agree_return_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.agree_return
     *
     * @mbggenerated Tue Jan 31 12:29:48 CST 2012
     */
    @Insert({
        "insert into edu.agree_return (agree_return_id, agree_return_name, ",
        "register_date, comment, ",
        "agree_copy)",
        "values (#{agree_return_id,jdbcType=NUMERIC}, #{agree_return_name,jdbcType=VARCHAR}, ",
        "#{register_date,jdbcType=TIMESTAMP}, #{comment,jdbcType=VARCHAR}, ",
        "#{agree_copy,jdbcType=BINARY})"
    })
    int insert(AgreeReturn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.agree_return
     *
     * @mbggenerated Tue Jan 31 12:29:48 CST 2012
     */
    int insertSelective(AgreeReturn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.agree_return
     *
     * @mbggenerated Tue Jan 31 12:29:48 CST 2012
     */
    List<AgreeReturn> selectByExampleWithBLOBs(AgreeReturnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.agree_return
     *
     * @mbggenerated Tue Jan 31 12:29:48 CST 2012
     */
    List<AgreeReturn> selectByExample(AgreeReturnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.agree_return
     *
     * @mbggenerated Tue Jan 31 12:29:48 CST 2012
     */
    @Select({
        "select",
        "agree_return_id, agree_return_name, register_date, comment, agree_copy",
        "from edu.agree_return",
        "where agree_return_id = #{agree_return_id,jdbcType=NUMERIC}"
    })
    @ResultMap("ResultMapWithBLOBs")
    AgreeReturn selectByPrimaryKey(Integer agree_return_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.agree_return
     *
     * @mbggenerated Tue Jan 31 12:29:48 CST 2012
     */
    int updateByExampleSelective(@Param("record") AgreeReturn record, @Param("example") AgreeReturnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.agree_return
     *
     * @mbggenerated Tue Jan 31 12:29:48 CST 2012
     */
    int updateByExampleWithBLOBs(@Param("record") AgreeReturn record, @Param("example") AgreeReturnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.agree_return
     *
     * @mbggenerated Tue Jan 31 12:29:48 CST 2012
     */
    int updateByExample(@Param("record") AgreeReturn record, @Param("example") AgreeReturnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.agree_return
     *
     * @mbggenerated Tue Jan 31 12:29:48 CST 2012
     */
    int updateByPrimaryKeySelective(AgreeReturn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.agree_return
     *
     * @mbggenerated Tue Jan 31 12:29:48 CST 2012
     */
    @Update({
        "update edu.agree_return",
        "set agree_return_name = #{agree_return_name,jdbcType=VARCHAR},",
          "register_date = #{register_date,jdbcType=TIMESTAMP},",
          "comment = #{comment,jdbcType=VARCHAR},",
          "agree_copy = #{agree_copy,jdbcType=BINARY}",
        "where agree_return_id = #{agree_return_id,jdbcType=NUMERIC}"
    })
    int updateByPrimaryKeyWithBLOBs(AgreeReturn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.agree_return
     *
     * @mbggenerated Tue Jan 31 12:29:48 CST 2012
     */
    @Update({
        "update edu.agree_return",
        "set agree_return_name = #{agree_return_name,jdbcType=VARCHAR},",
          "register_date = #{register_date,jdbcType=TIMESTAMP},",
          "comment = #{comment,jdbcType=VARCHAR}",
        "where agree_return_id = #{agree_return_id,jdbcType=NUMERIC}"
    })
    int updateByPrimaryKey(AgreeReturn record);
}