package com.brightedu.dao.edu;

import com.brightedu.model.edu.BankAccount;
import com.brightedu.model.edu.BankAccountExample;
import com.brightedu.model.edu.BankAccountKey;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface BankAccountMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table edu.bank_account
	 * @mbggenerated  Sat Feb 11 02:04:14 CST 2012
	 */
	int countByExample(BankAccountExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table edu.bank_account
	 * @mbggenerated  Sat Feb 11 02:04:14 CST 2012
	 */
	int deleteByExample(BankAccountExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table edu.bank_account
	 * @mbggenerated  Sat Feb 11 02:04:14 CST 2012
	 */
	@Delete({ "delete from edu.bank_account",
			"where agent_id = #{agent_id,jdbcType=NUMERIC}",
			"and college_id = #{college_id,jdbcType=NUMERIC}",
			"and batch_id = #{batch_id,jdbcType=NUMERIC}" })
	int deleteByPrimaryKey(BankAccountKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table edu.bank_account
	 * @mbggenerated  Sat Feb 11 02:04:14 CST 2012
	 */
	@Insert({
			"insert into edu.bank_account (agent_id, college_id, ",
			"batch_id, account, ",
			"register_date)",
			"values (#{agent_id,jdbcType=NUMERIC}, #{college_id,jdbcType=NUMERIC}, ",
			"#{batch_id,jdbcType=NUMERIC}, #{account,jdbcType=VARCHAR}, ",
			"#{register_date,jdbcType=TIMESTAMP})" })
	int insert(BankAccount record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table edu.bank_account
	 * @mbggenerated  Sat Feb 11 02:04:14 CST 2012
	 */
	int insertSelective(BankAccount record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table edu.bank_account
	 * @mbggenerated  Sat Feb 11 02:04:14 CST 2012
	 */
	List<BankAccount> selectByExample(BankAccountExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table edu.bank_account
	 * @mbggenerated  Sat Feb 11 02:04:14 CST 2012
	 */
	@Select({ "select",
			"agent_id, college_id, batch_id, account, register_date",
			"from edu.bank_account",
			"where agent_id = #{agent_id,jdbcType=NUMERIC}",
			"and college_id = #{college_id,jdbcType=NUMERIC}",
			"and batch_id = #{batch_id,jdbcType=NUMERIC}" })
	@ResultMap("BaseResultMap")
	BankAccount selectByPrimaryKey(BankAccountKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table edu.bank_account
	 * @mbggenerated  Sat Feb 11 02:04:14 CST 2012
	 */
	int updateByExampleSelective(@Param("record") BankAccount record,
			@Param("example") BankAccountExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table edu.bank_account
	 * @mbggenerated  Sat Feb 11 02:04:14 CST 2012
	 */
	int updateByExample(@Param("record") BankAccount record,
			@Param("example") BankAccountExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table edu.bank_account
	 * @mbggenerated  Sat Feb 11 02:04:14 CST 2012
	 */
	int updateByPrimaryKeySelective(BankAccount record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table edu.bank_account
	 * @mbggenerated  Sat Feb 11 02:04:14 CST 2012
	 */
	@Update({ "update edu.bank_account",
			"set account = #{account,jdbcType=VARCHAR},",
			"register_date = #{register_date,jdbcType=TIMESTAMP}",
			"where agent_id = #{agent_id,jdbcType=NUMERIC}",
			"and college_id = #{college_id,jdbcType=NUMERIC}",
			"and batch_id = #{batch_id,jdbcType=NUMERIC}" })
	int updateByPrimaryKey(BankAccount record);
}