package com.brightedu.dao.edu;

import com.brightedu.model.edu.ChargeAdmin;
import com.brightedu.model.edu.ChargeAdminExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface ChargeAdminMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table edu.charge_admin
	 * @mbggenerated  Tue Jan 31 12:29:48 CST 2012
	 */
	int countByExample(ChargeAdminExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table edu.charge_admin
	 * @mbggenerated  Tue Jan 31 12:29:48 CST 2012
	 */
	int deleteByExample(ChargeAdminExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table edu.charge_admin
	 * @mbggenerated  Tue Jan 31 12:29:48 CST 2012
	 */
	@Delete({ "delete from edu.charge_admin",
			"where student_id = #{student_id,jdbcType=NUMERIC}" })
	int deleteByPrimaryKey(Integer student_id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table edu.charge_admin
	 * @mbggenerated  Tue Jan 31 12:29:48 CST 2012
	 */
	@Insert({
			"insert into edu.charge_admin (student_id, fee_need, ",
			"derate_id, charge_fee_paid, ",
			"refund_id, register_date, ",
			"update_date)",
			"values (#{student_id,jdbcType=NUMERIC}, #{fee_need,jdbcType=NUMERIC}, ",
			"#{derate_id,jdbcType=NUMERIC}, #{charge_fee_paid,jdbcType=NUMERIC}, ",
			"#{refund_id,jdbcType=NUMERIC}, #{register_date,jdbcType=TIMESTAMP}, ",
			"#{update_date,jdbcType=TIMESTAMP})" })
	int insert(ChargeAdmin record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table edu.charge_admin
	 * @mbggenerated  Tue Jan 31 12:29:48 CST 2012
	 */
	int insertSelective(ChargeAdmin record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table edu.charge_admin
	 * @mbggenerated  Tue Jan 31 12:29:48 CST 2012
	 */
	List<ChargeAdmin> selectByExample(ChargeAdminExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table edu.charge_admin
	 * @mbggenerated  Tue Jan 31 12:29:48 CST 2012
	 */
	@Select({
			"select",
			"student_id, fee_need, derate_id, charge_fee_paid, refund_id, register_date, ",
			"update_date", "from edu.charge_admin",
			"where student_id = #{student_id,jdbcType=NUMERIC}" })
	@ResultMap("BaseResultMap")
	ChargeAdmin selectByPrimaryKey(Integer student_id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table edu.charge_admin
	 * @mbggenerated  Tue Jan 31 12:29:48 CST 2012
	 */
	int updateByExampleSelective(@Param("record") ChargeAdmin record,
			@Param("example") ChargeAdminExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table edu.charge_admin
	 * @mbggenerated  Tue Jan 31 12:29:48 CST 2012
	 */
	int updateByExample(@Param("record") ChargeAdmin record,
			@Param("example") ChargeAdminExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table edu.charge_admin
	 * @mbggenerated  Tue Jan 31 12:29:48 CST 2012
	 */
	int updateByPrimaryKeySelective(ChargeAdmin record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table edu.charge_admin
	 * @mbggenerated  Tue Jan 31 12:29:48 CST 2012
	 */
	@Update({ "update edu.charge_admin",
			"set fee_need = #{fee_need,jdbcType=NUMERIC},",
			"derate_id = #{derate_id,jdbcType=NUMERIC},",
			"charge_fee_paid = #{charge_fee_paid,jdbcType=NUMERIC},",
			"refund_id = #{refund_id,jdbcType=NUMERIC},",
			"register_date = #{register_date,jdbcType=TIMESTAMP},",
			"update_date = #{update_date,jdbcType=TIMESTAMP}",
			"where student_id = #{student_id,jdbcType=NUMERIC}" })
	int updateByPrimaryKey(ChargeAdmin record);
}