package com.brightedu.dao.edu;

import com.brightedu.model.edu.ChargeAdmin;
import com.brightedu.model.edu.ChargeAdminExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface ChargeAdminMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table edu.charge_admin
	 * @mbggenerated  Thu Feb 09 18:41:46 CST 2012
	 */
	int countByExample(ChargeAdminExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table edu.charge_admin
	 * @mbggenerated  Thu Feb 09 18:41:46 CST 2012
	 */
	int deleteByExample(ChargeAdminExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table edu.charge_admin
	 * @mbggenerated  Thu Feb 09 18:41:46 CST 2012
	 */
	@Delete({ "delete from edu.charge_admin",
			"where charge_id = #{charge_id,jdbcType=NUMERIC}" })
	int deleteByPrimaryKey(Integer charge_id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table edu.charge_admin
	 * @mbggenerated  Thu Feb 09 18:41:46 CST 2012
	 */
	@Insert({
			"insert into edu.charge_admin (charge_id, student_id, ",
			"fee_id, charge_type_id, ",
			"bank_code, amount_flag, ",
			"amount, charge_time, ",
			"remark)",
			"values (#{charge_id,jdbcType=NUMERIC}, #{student_id,jdbcType=NUMERIC}, ",
			"#{fee_id,jdbcType=NUMERIC}, #{charge_type_id,jdbcType=NUMERIC}, ",
			"#{bank_code,jdbcType=VARCHAR}, #{amount_flag,jdbcType=BIT}, ",
			"#{amount,jdbcType=NUMERIC}, #{charge_time,jdbcType=TIMESTAMP}, ",
			"#{remark,jdbcType=VARCHAR})" })
	int insert(ChargeAdmin record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table edu.charge_admin
	 * @mbggenerated  Thu Feb 09 18:41:46 CST 2012
	 */
	int insertSelective(ChargeAdmin record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table edu.charge_admin
	 * @mbggenerated  Thu Feb 09 18:41:46 CST 2012
	 */
	List<ChargeAdmin> selectByExample(ChargeAdminExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table edu.charge_admin
	 * @mbggenerated  Thu Feb 09 18:41:46 CST 2012
	 */
	@Select({
			"select",
			"charge_id, student_id, fee_id, charge_type_id, bank_code, amount_flag, amount, ",
			"charge_time, remark", "from edu.charge_admin",
			"where charge_id = #{charge_id,jdbcType=NUMERIC}" })
	@ResultMap("BaseResultMap")
	ChargeAdmin selectByPrimaryKey(Integer charge_id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table edu.charge_admin
	 * @mbggenerated  Thu Feb 09 18:41:46 CST 2012
	 */
	int updateByExampleSelective(@Param("record") ChargeAdmin record,
			@Param("example") ChargeAdminExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table edu.charge_admin
	 * @mbggenerated  Thu Feb 09 18:41:46 CST 2012
	 */
	int updateByExample(@Param("record") ChargeAdmin record,
			@Param("example") ChargeAdminExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table edu.charge_admin
	 * @mbggenerated  Thu Feb 09 18:41:46 CST 2012
	 */
	int updateByPrimaryKeySelective(ChargeAdmin record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table edu.charge_admin
	 * @mbggenerated  Thu Feb 09 18:41:46 CST 2012
	 */
	@Update({ "update edu.charge_admin",
			"set student_id = #{student_id,jdbcType=NUMERIC},",
			"fee_id = #{fee_id,jdbcType=NUMERIC},",
			"charge_type_id = #{charge_type_id,jdbcType=NUMERIC},",
			"bank_code = #{bank_code,jdbcType=VARCHAR},",
			"amount_flag = #{amount_flag,jdbcType=BIT},",
			"amount = #{amount,jdbcType=NUMERIC},",
			"charge_time = #{charge_time,jdbcType=TIMESTAMP},",
			"remark = #{remark,jdbcType=VARCHAR}",
			"where charge_id = #{charge_id,jdbcType=NUMERIC}" })
	int updateByPrimaryKey(ChargeAdmin record);
}