package com.brightedu.dao.edu;

import com.brightedu.model.edu.CollegeReturn;
import com.brightedu.model.edu.CollegeReturnExample;
import com.brightedu.model.edu.CollegeReturnKey;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface CollegeReturnMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.college_return
     *
     * @mbggenerated Thu Feb 09 18:11:26 CST 2012
     */
    int countByExample(CollegeReturnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.college_return
     *
     * @mbggenerated Thu Feb 09 18:11:26 CST 2012
     */
    int deleteByExample(CollegeReturnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.college_return
     *
     * @mbggenerated Thu Feb 09 18:11:26 CST 2012
     */
    @Delete({
        "delete from edu.college_return",
        "where agreement_id = #{agreement_id,jdbcType=NUMERIC}",
          "and headcount = #{headcount,jdbcType=NUMERIC}",
          "and batch_id = #{batch_id,jdbcType=NUMERIC}"
    })
    int deleteByPrimaryKey(CollegeReturnKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.college_return
     *
     * @mbggenerated Thu Feb 09 18:11:26 CST 2012
     */
    @Insert({
        "insert into edu.college_return (agreement_id, headcount, ",
        "batch_id, fee_id, ",
        "return_percent, register_date, ",
        "update_date)",
        "values (#{agreement_id,jdbcType=NUMERIC}, #{headcount,jdbcType=NUMERIC}, ",
        "#{batch_id,jdbcType=NUMERIC}, #{fee_id,jdbcType=NUMERIC}, ",
        "#{return_percent,jdbcType=NUMERIC}, #{register_date,jdbcType=TIMESTAMP}, ",
        "#{update_date,jdbcType=TIMESTAMP})"
    })
    int insert(CollegeReturn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.college_return
     *
     * @mbggenerated Thu Feb 09 18:11:26 CST 2012
     */
    int insertSelective(CollegeReturn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.college_return
     *
     * @mbggenerated Thu Feb 09 18:11:26 CST 2012
     */
    List<CollegeReturn> selectByExample(CollegeReturnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.college_return
     *
     * @mbggenerated Thu Feb 09 18:11:26 CST 2012
     */
    @Select({
        "select",
        "agreement_id, headcount, batch_id, fee_id, return_percent, register_date, update_date",
        "from edu.college_return",
        "where agreement_id = #{agreement_id,jdbcType=NUMERIC}",
          "and headcount = #{headcount,jdbcType=NUMERIC}",
          "and batch_id = #{batch_id,jdbcType=NUMERIC}"
    })
    @ResultMap("BaseResultMap")
    CollegeReturn selectByPrimaryKey(CollegeReturnKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.college_return
     *
     * @mbggenerated Thu Feb 09 18:11:26 CST 2012
     */
    int updateByExampleSelective(@Param("record") CollegeReturn record, @Param("example") CollegeReturnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.college_return
     *
     * @mbggenerated Thu Feb 09 18:11:26 CST 2012
     */
    int updateByExample(@Param("record") CollegeReturn record, @Param("example") CollegeReturnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.college_return
     *
     * @mbggenerated Thu Feb 09 18:11:26 CST 2012
     */
    int updateByPrimaryKeySelective(CollegeReturn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.college_return
     *
     * @mbggenerated Thu Feb 09 18:11:26 CST 2012
     */
    @Update({
        "update edu.college_return",
        "set fee_id = #{fee_id,jdbcType=NUMERIC},",
          "return_percent = #{return_percent,jdbcType=NUMERIC},",
          "register_date = #{register_date,jdbcType=TIMESTAMP},",
          "update_date = #{update_date,jdbcType=TIMESTAMP}",
        "where agreement_id = #{agreement_id,jdbcType=NUMERIC}",
          "and headcount = #{headcount,jdbcType=NUMERIC}",
          "and batch_id = #{batch_id,jdbcType=NUMERIC}"
    })
    int updateByPrimaryKey(CollegeReturn record);
}