package com.brightedu.dao.edu;

import com.brightedu.model.edu.CollegeAgreement;
import com.brightedu.model.edu.CollegeAgreementExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;


public interface CollegeAgreementMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table edu.college_agreement
	 * @mbggenerated  Thu Feb 02 16:54:43 CST 2012
	 */
	int countByExample(CollegeAgreementExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table edu.college_agreement
	 * @mbggenerated  Thu Feb 02 16:54:43 CST 2012
	 */
	int deleteByExample(CollegeAgreementExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table edu.college_agreement
	 * @mbggenerated  Thu Feb 02 16:54:43 CST 2012
	 */
	@Delete({ "delete from edu.college_agreement",
			"where agreement_id = #{agreement_id,jdbcType=NUMERIC}" })
	int deleteByPrimaryKey(Integer agreement_id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table edu.college_agreement
	 * @mbggenerated  Thu Feb 02 16:54:43 CST 2012
	 */
	@Insert({
			"insert into edu.college_agreement (agreement_id, college_id, ",
			"agent_id, agreement_status, ",
			"user_id, register_date, ",
			"update_date, agreement)",
			"values (#{agreement_id,jdbcType=NUMERIC}, #{college_id,jdbcType=NUMERIC}, ",
			"#{agent_id,jdbcType=NUMERIC}, #{agreement_status,jdbcType=BIT}, ",
			"#{user_id,jdbcType=NUMERIC}, #{register_date,jdbcType=TIMESTAMP}, ",
			"#{update_date,jdbcType=TIMESTAMP}, #{agreement,jdbcType=BINARY})" })
	int insert(CollegeAgreement record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table edu.college_agreement
	 * @mbggenerated  Thu Feb 02 16:54:43 CST 2012
	 */
	int insertSelective(CollegeAgreement record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table edu.college_agreement
	 * @mbggenerated  Thu Feb 02 16:54:43 CST 2012
	 */
	List<CollegeAgreement> selectByExampleWithBLOBs(
			CollegeAgreementExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table edu.college_agreement
	 * @mbggenerated  Thu Feb 02 16:54:43 CST 2012
	 */
	List<CollegeAgreement> selectByExample(CollegeAgreementExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table edu.college_agreement
	 * @mbggenerated  Thu Feb 02 16:54:43 CST 2012
	 */
	@Select({
			"select",
			"agreement_id, college_id, agent_id, agreement_status, user_id, register_date, ",
			"update_date, agreement", "from edu.college_agreement",
			"where agreement_id = #{agreement_id,jdbcType=NUMERIC}" })
	@ResultMap("ResultMapWithBLOBs")
	CollegeAgreement selectByPrimaryKey(Integer agreement_id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table edu.college_agreement
	 * @mbggenerated  Thu Feb 02 16:54:43 CST 2012
	 */
	int updateByExampleSelective(@Param("record") CollegeAgreement record,
			@Param("example") CollegeAgreementExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table edu.college_agreement
	 * @mbggenerated  Thu Feb 02 16:54:43 CST 2012
	 */
	int updateByExampleWithBLOBs(@Param("record") CollegeAgreement record,
			@Param("example") CollegeAgreementExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table edu.college_agreement
	 * @mbggenerated  Thu Feb 02 16:54:43 CST 2012
	 */
	int updateByExample(@Param("record") CollegeAgreement record,
			@Param("example") CollegeAgreementExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table edu.college_agreement
	 * @mbggenerated  Thu Feb 02 16:54:43 CST 2012
	 */
	int updateByPrimaryKeySelective(CollegeAgreement record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table edu.college_agreement
	 * @mbggenerated  Thu Feb 02 16:54:43 CST 2012
	 */
	@Update({ "update edu.college_agreement",
			"set college_id = #{college_id,jdbcType=NUMERIC},",
			"agent_id = #{agent_id,jdbcType=NUMERIC},",
			"agreement_status = #{agreement_status,jdbcType=BIT},",
			"user_id = #{user_id,jdbcType=NUMERIC},",
			"register_date = #{register_date,jdbcType=TIMESTAMP},",
			"update_date = #{update_date,jdbcType=TIMESTAMP},",
			"agreement = #{agreement,jdbcType=BINARY}",
			"where agreement_id = #{agreement_id,jdbcType=NUMERIC}" })
	int updateByPrimaryKeyWithBLOBs(CollegeAgreement record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table edu.college_agreement
	 * @mbggenerated  Thu Feb 02 16:54:43 CST 2012
	 */
	@Update({ "update edu.college_agreement",
			"set college_id = #{college_id,jdbcType=NUMERIC},",
			"agent_id = #{agent_id,jdbcType=NUMERIC},",
			"agreement_status = #{agreement_status,jdbcType=BIT},",
			"user_id = #{user_id,jdbcType=NUMERIC},",
			"register_date = #{register_date,jdbcType=TIMESTAMP},",
			"update_date = #{update_date,jdbcType=TIMESTAMP}",
			"where agreement_id = #{agreement_id,jdbcType=NUMERIC}" })
	int updateByPrimaryKey(CollegeAgreement record);
}