package com.brightedu.dao.edu;

import com.brightedu.model.edu.CollegeSubject;
import com.brightedu.model.edu.CollegeSubjectExample;
import com.brightedu.model.edu.CollegeSubjectKey;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface CollegeSubjectMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table edu.college_subject
	 * @mbggenerated  Tue Feb 21 13:01:30 CST 2012
	 */
	int countByExample(CollegeSubjectExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table edu.college_subject
	 * @mbggenerated  Tue Feb 21 13:01:30 CST 2012
	 */
	int deleteByExample(CollegeSubjectExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table edu.college_subject
	 * @mbggenerated  Tue Feb 21 13:01:30 CST 2012
	 */
	@Delete({ "delete from edu.college_subject",
			"where college_id = #{college_id,jdbcType=NUMERIC}",
			"and batch_id = #{batch_id,jdbcType=NUMERIC}",
			"and classified_id = #{classified_id,jdbcType=NUMERIC}",
			"and subeject_id = #{subeject_id,jdbcType=NUMERIC}" })
	int deleteByPrimaryKey(CollegeSubjectKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table edu.college_subject
	 * @mbggenerated  Tue Feb 21 13:01:30 CST 2012
	 */
	@Insert({
			"insert into edu.college_subject (college_id, batch_id, ",
			"classified_id, subeject_id, ",
			"length_of_schooling, register_date)",
			"values (#{college_id,jdbcType=NUMERIC}, #{batch_id,jdbcType=NUMERIC}, ",
			"#{classified_id,jdbcType=NUMERIC}, #{subeject_id,jdbcType=NUMERIC}, ",
			"#{length_of_schooling,jdbcType=NUMERIC}, #{register_date,jdbcType=TIMESTAMP})" })
	int insert(CollegeSubject record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table edu.college_subject
	 * @mbggenerated  Tue Feb 21 13:01:30 CST 2012
	 */
	int insertSelective(CollegeSubject record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table edu.college_subject
	 * @mbggenerated  Tue Feb 21 13:01:30 CST 2012
	 */
	List<CollegeSubject> selectByExample(CollegeSubjectExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table edu.college_subject
	 * @mbggenerated  Tue Feb 21 13:01:30 CST 2012
	 */
	@Select({
			"select",
			"college_id, batch_id, classified_id, subeject_id, length_of_schooling, register_date",
			"from edu.college_subject",
			"where college_id = #{college_id,jdbcType=NUMERIC}",
			"and batch_id = #{batch_id,jdbcType=NUMERIC}",
			"and classified_id = #{classified_id,jdbcType=NUMERIC}",
			"and subeject_id = #{subeject_id,jdbcType=NUMERIC}" })
	@ResultMap("BaseResultMap")
	CollegeSubject selectByPrimaryKey(CollegeSubjectKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table edu.college_subject
	 * @mbggenerated  Tue Feb 21 13:01:30 CST 2012
	 */
	int updateByExampleSelective(@Param("record") CollegeSubject record,
			@Param("example") CollegeSubjectExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table edu.college_subject
	 * @mbggenerated  Tue Feb 21 13:01:30 CST 2012
	 */
	int updateByExample(@Param("record") CollegeSubject record,
			@Param("example") CollegeSubjectExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table edu.college_subject
	 * @mbggenerated  Tue Feb 21 13:01:30 CST 2012
	 */
	int updateByPrimaryKeySelective(CollegeSubject record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table edu.college_subject
	 * @mbggenerated  Tue Feb 21 13:01:30 CST 2012
	 */
	@Update({
			"update edu.college_subject",
			"set length_of_schooling = #{length_of_schooling,jdbcType=NUMERIC},",
			"register_date = #{register_date,jdbcType=TIMESTAMP}",
			"where college_id = #{college_id,jdbcType=NUMERIC}",
			"and batch_id = #{batch_id,jdbcType=NUMERIC}",
			"and classified_id = #{classified_id,jdbcType=NUMERIC}",
			"and subeject_id = #{subeject_id,jdbcType=NUMERIC}" })
	int updateByPrimaryKey(CollegeSubject record);
}