package com.brightedu.dao.edu;

import com.brightedu.model.edu.CollegeAggregation;
import com.brightedu.model.edu.CollegeAggregationExample;
import com.brightedu.model.edu.CollegeAggregationKey;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface CollegeAggregationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.college_aggregation
     *
     * @mbggenerated Tue Feb 21 21:53:42 CST 2012
     */
    int countByExample(CollegeAggregationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.college_aggregation
     *
     * @mbggenerated Tue Feb 21 21:53:42 CST 2012
     */
    int deleteByExample(CollegeAggregationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.college_aggregation
     *
     * @mbggenerated Tue Feb 21 21:53:42 CST 2012
     */
    @Delete({
        "delete from edu.college_aggregation",
        "where ag_return_type_id = #{ag_return_type_id,jdbcType=NUMERIC}",
          "and college_id = #{college_id,jdbcType=NUMERIC}",
          "and headcount = #{headcount,jdbcType=NUMERIC}"
    })
    int deleteByPrimaryKey(CollegeAggregationKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.college_aggregation
     *
     * @mbggenerated Tue Feb 21 21:53:42 CST 2012
     */
    @Insert({
        "insert into edu.college_aggregation (ag_return_type_id, college_id, ",
        "headcount, return_percent)",
        "values (#{ag_return_type_id,jdbcType=NUMERIC}, #{college_id,jdbcType=NUMERIC}, ",
        "#{headcount,jdbcType=NUMERIC}, #{return_percent,jdbcType=NUMERIC})"
    })
    int insert(CollegeAggregation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.college_aggregation
     *
     * @mbggenerated Tue Feb 21 21:53:42 CST 2012
     */
    int insertSelective(CollegeAggregation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.college_aggregation
     *
     * @mbggenerated Tue Feb 21 21:53:42 CST 2012
     */
    List<CollegeAggregation> selectByExample(CollegeAggregationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.college_aggregation
     *
     * @mbggenerated Tue Feb 21 21:53:42 CST 2012
     */
    @Select({
        "select",
        "ag_return_type_id, college_id, headcount, return_percent",
        "from edu.college_aggregation",
        "where ag_return_type_id = #{ag_return_type_id,jdbcType=NUMERIC}",
          "and college_id = #{college_id,jdbcType=NUMERIC}",
          "and headcount = #{headcount,jdbcType=NUMERIC}"
    })
    @ResultMap("BaseResultMap")
    CollegeAggregation selectByPrimaryKey(CollegeAggregationKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.college_aggregation
     *
     * @mbggenerated Tue Feb 21 21:53:42 CST 2012
     */
    int updateByExampleSelective(@Param("record") CollegeAggregation record, @Param("example") CollegeAggregationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.college_aggregation
     *
     * @mbggenerated Tue Feb 21 21:53:42 CST 2012
     */
    int updateByExample(@Param("record") CollegeAggregation record, @Param("example") CollegeAggregationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.college_aggregation
     *
     * @mbggenerated Tue Feb 21 21:53:42 CST 2012
     */
    int updateByPrimaryKeySelective(CollegeAggregation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.college_aggregation
     *
     * @mbggenerated Tue Feb 21 21:53:42 CST 2012
     */
    @Update({
        "update edu.college_aggregation",
        "set return_percent = #{return_percent,jdbcType=NUMERIC}",
        "where ag_return_type_id = #{ag_return_type_id,jdbcType=NUMERIC}",
          "and college_id = #{college_id,jdbcType=NUMERIC}",
          "and headcount = #{headcount,jdbcType=NUMERIC}"
    })
    int updateByPrimaryKey(CollegeAggregation record);
}