package com.brightedu.dao.edu;

import com.brightedu.model.edu.CollegeSubjectView;
import com.brightedu.model.edu.CollegeSubjectViewExample;
import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;

public interface CollegeSubjectViewMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.college_subject_view
     *
     * @mbggenerated Tue Feb 14 14:52:13 CST 2012
     */
    int countByExample(CollegeSubjectViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.college_subject_view
     *
     * @mbggenerated Tue Feb 14 14:52:13 CST 2012
     */
    int deleteByExample(CollegeSubjectViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.college_subject_view
     *
     * @mbggenerated Tue Feb 14 14:52:13 CST 2012
     */
    @Insert({
        "insert into edu.college_subject_view (college_id, batch_id, ",
        "classified_id, subeject_id, ",
        "subject_name, length_of_schooling)",
        "values (#{college_id,jdbcType=NUMERIC}, #{batch_id,jdbcType=NUMERIC}, ",
        "#{classified_id,jdbcType=NUMERIC}, #{subeject_id,jdbcType=NUMERIC}, ",
        "#{subject_name,jdbcType=VARCHAR}, #{length_of_schooling,jdbcType=NUMERIC})"
    })
    int insert(CollegeSubjectView record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.college_subject_view
     *
     * @mbggenerated Tue Feb 14 14:52:13 CST 2012
     */
    int insertSelective(CollegeSubjectView record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.college_subject_view
     *
     * @mbggenerated Tue Feb 14 14:52:13 CST 2012
     */
    List<CollegeSubjectView> selectByExample(CollegeSubjectViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.college_subject_view
     *
     * @mbggenerated Tue Feb 14 14:52:13 CST 2012
     */
    int updateByExampleSelective(@Param("record") CollegeSubjectView record, @Param("example") CollegeSubjectViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.college_subject_view
     *
     * @mbggenerated Tue Feb 14 14:52:13 CST 2012
     */
    int updateByExample(@Param("record") CollegeSubjectView record, @Param("example") CollegeSubjectViewExample example);
}