package com.brightedu.dao.edu;

import com.brightedu.model.edu.CurrentBatch;
import com.brightedu.model.edu.CurrentBatchExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface CurrentBatchMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.current_batch
     *
     * @mbggenerated Mon Feb 13 17:13:20 CST 2012
     */
    int countByExample(CurrentBatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.current_batch
     *
     * @mbggenerated Mon Feb 13 17:13:20 CST 2012
     */
    int deleteByExample(CurrentBatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.current_batch
     *
     * @mbggenerated Mon Feb 13 17:13:20 CST 2012
     */
    @Delete({
        "delete from edu.current_batch",
        "where current_batch_id = #{current_batch_id,jdbcType=NUMERIC}"
    })
    int deleteByPrimaryKey(Integer current_batch_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.current_batch
     *
     * @mbggenerated Mon Feb 13 17:13:20 CST 2012
     */
    @Insert({
        "insert into edu.current_batch (current_batch_id, update_date)",
        "values (#{current_batch_id,jdbcType=NUMERIC}, #{update_date,jdbcType=TIMESTAMP})"
    })
    int insert(CurrentBatch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.current_batch
     *
     * @mbggenerated Mon Feb 13 17:13:20 CST 2012
     */
    int insertSelective(CurrentBatch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.current_batch
     *
     * @mbggenerated Mon Feb 13 17:13:20 CST 2012
     */
    List<CurrentBatch> selectByExample(CurrentBatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.current_batch
     *
     * @mbggenerated Mon Feb 13 17:13:20 CST 2012
     */
    @Select({
        "select",
        "current_batch_id, update_date",
        "from edu.current_batch",
        "where current_batch_id = #{current_batch_id,jdbcType=NUMERIC}"
    })
    @ResultMap("BaseResultMap")
    CurrentBatch selectByPrimaryKey(Integer current_batch_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.current_batch
     *
     * @mbggenerated Mon Feb 13 17:13:20 CST 2012
     */
    int updateByExampleSelective(@Param("record") CurrentBatch record, @Param("example") CurrentBatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.current_batch
     *
     * @mbggenerated Mon Feb 13 17:13:20 CST 2012
     */
    int updateByExample(@Param("record") CurrentBatch record, @Param("example") CurrentBatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.current_batch
     *
     * @mbggenerated Mon Feb 13 17:13:20 CST 2012
     */
    int updateByPrimaryKeySelective(CurrentBatch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.current_batch
     *
     * @mbggenerated Mon Feb 13 17:13:20 CST 2012
     */
    @Update({
        "update edu.current_batch",
        "set update_date = #{update_date,jdbcType=TIMESTAMP}",
        "where current_batch_id = #{current_batch_id,jdbcType=NUMERIC}"
    })
    int updateByPrimaryKey(CurrentBatch record);
}