package com.brightedu.dao.edu;

import com.brightedu.model.edu.EntranceCost;
import com.brightedu.model.edu.EntranceCostExample;
import com.brightedu.model.edu.EntranceCostKey;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface EntranceCostMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.entrance_cost
     *
     * @mbggenerated Sun Jan 15 18:52:28 CST 2012
     */
    int countByExample(EntranceCostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.entrance_cost
     *
     * @mbggenerated Sun Jan 15 18:52:28 CST 2012
     */
    int deleteByExample(EntranceCostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.entrance_cost
     *
     * @mbggenerated Sun Jan 15 18:52:28 CST 2012
     */
    @Delete({
        "delete from edu.entrance_cost",
        "where college_id = #{college_id,jdbcType=NUMERIC}",
          "and batch_id = #{batch_id,jdbcType=NUMERIC}",
          "and subject_id = #{subject_id,jdbcType=NUMERIC}"
    })
    int deleteByPrimaryKey(EntranceCostKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.entrance_cost
     *
     * @mbggenerated Sun Jan 15 18:52:28 CST 2012
     */
    @Insert({
        "insert into edu.entrance_cost (college_id, batch_id, ",
        "subject_id, register_date, ",
        "fee_id, fee)",
        "values (#{college_id,jdbcType=NUMERIC}, #{batch_id,jdbcType=NUMERIC}, ",
        "#{subject_id,jdbcType=NUMERIC}, #{register_date,jdbcType=TIMESTAMP}, ",
        "#{fee_id,jdbcType=NUMERIC}, #{fee,jdbcType=NUMERIC})"
    })
    int insert(EntranceCost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.entrance_cost
     *
     * @mbggenerated Sun Jan 15 18:52:28 CST 2012
     */
    int insertSelective(EntranceCost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.entrance_cost
     *
     * @mbggenerated Sun Jan 15 18:52:28 CST 2012
     */
    List<EntranceCost> selectByExample(EntranceCostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.entrance_cost
     *
     * @mbggenerated Sun Jan 15 18:52:28 CST 2012
     */
    @Select({
        "select",
        "college_id, batch_id, subject_id, register_date, fee_id, fee",
        "from edu.entrance_cost",
        "where college_id = #{college_id,jdbcType=NUMERIC}",
          "and batch_id = #{batch_id,jdbcType=NUMERIC}",
          "and subject_id = #{subject_id,jdbcType=NUMERIC}"
    })
    @ResultMap("BaseResultMap")
    EntranceCost selectByPrimaryKey(EntranceCostKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.entrance_cost
     *
     * @mbggenerated Sun Jan 15 18:52:28 CST 2012
     */
    int updateByExampleSelective(@Param("record") EntranceCost record, @Param("example") EntranceCostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.entrance_cost
     *
     * @mbggenerated Sun Jan 15 18:52:28 CST 2012
     */
    int updateByExample(@Param("record") EntranceCost record, @Param("example") EntranceCostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.entrance_cost
     *
     * @mbggenerated Sun Jan 15 18:52:28 CST 2012
     */
    int updateByPrimaryKeySelective(EntranceCost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.entrance_cost
     *
     * @mbggenerated Sun Jan 15 18:52:28 CST 2012
     */
    @Update({
        "update edu.entrance_cost",
        "set register_date = #{register_date,jdbcType=TIMESTAMP},",
          "fee_id = #{fee_id,jdbcType=NUMERIC},",
          "fee = #{fee,jdbcType=NUMERIC}",
        "where college_id = #{college_id,jdbcType=NUMERIC}",
          "and batch_id = #{batch_id,jdbcType=NUMERIC}",
          "and subject_id = #{subject_id,jdbcType=NUMERIC}"
    })
    int updateByPrimaryKey(EntranceCost record);
}