package com.brightedu.dao.edu;

import com.brightedu.model.edu.MajorCategory;
import com.brightedu.model.edu.MajorCategoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface MajorCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.student_major_category
     *
     * @mbggenerated Sun Feb 12 12:25:52 CST 2012
     */
    int countByExample(MajorCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.student_major_category
     *
     * @mbggenerated Sun Feb 12 12:25:52 CST 2012
     */
    int deleteByExample(MajorCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.student_major_category
     *
     * @mbggenerated Sun Feb 12 12:25:52 CST 2012
     */
    @Delete({
        "delete from edu.student_major_category",
        "where student_major_category_id = #{student_major_category_id,jdbcType=NUMERIC}"
    })
    int deleteByPrimaryKey(Integer student_major_category_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.student_major_category
     *
     * @mbggenerated Sun Feb 12 12:25:52 CST 2012
     */
    @Insert({
        "insert into edu.student_major_category (student_major_category_id, student_major_category_name)",
        "values (#{student_major_category_id,jdbcType=NUMERIC}, #{student_major_category_name,jdbcType=VARCHAR})"
    })
    int insert(MajorCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.student_major_category
     *
     * @mbggenerated Sun Feb 12 12:25:52 CST 2012
     */
    int insertSelective(MajorCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.student_major_category
     *
     * @mbggenerated Sun Feb 12 12:25:52 CST 2012
     */
    List<MajorCategory> selectByExample(MajorCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.student_major_category
     *
     * @mbggenerated Sun Feb 12 12:25:52 CST 2012
     */
    @Select({
        "select",
        "student_major_category_id, student_major_category_name",
        "from edu.student_major_category",
        "where student_major_category_id = #{student_major_category_id,jdbcType=NUMERIC}"
    })
    @ResultMap("BaseResultMap")
    MajorCategory selectByPrimaryKey(Integer student_major_category_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.student_major_category
     *
     * @mbggenerated Sun Feb 12 12:25:52 CST 2012
     */
    int updateByExampleSelective(@Param("record") MajorCategory record, @Param("example") MajorCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.student_major_category
     *
     * @mbggenerated Sun Feb 12 12:25:52 CST 2012
     */
    int updateByExample(@Param("record") MajorCategory record, @Param("example") MajorCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.student_major_category
     *
     * @mbggenerated Sun Feb 12 12:25:52 CST 2012
     */
    int updateByPrimaryKeySelective(MajorCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.student_major_category
     *
     * @mbggenerated Sun Feb 12 12:25:52 CST 2012
     */
    @Update({
        "update edu.student_major_category",
        "set student_major_category_name = #{student_major_category_name,jdbcType=VARCHAR}",
        "where student_major_category_id = #{student_major_category_id,jdbcType=NUMERIC}"
    })
    int updateByPrimaryKey(MajorCategory record);
}