package com.brightedu.dao.edu;

import com.brightedu.model.edu.MessageReal;
import com.brightedu.model.edu.MessageRealExample;
import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;

public interface MessageRealMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table edu.messages_real
	 * @mbggenerated  Tue Feb 28 16:17:24 CST 2012
	 */
	int countByExample(MessageRealExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table edu.messages_real
	 * @mbggenerated  Tue Feb 28 16:17:24 CST 2012
	 */
	int deleteByExample(MessageRealExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table edu.messages_real
	 * @mbggenerated  Tue Feb 28 16:17:24 CST 2012
	 */
	@Insert({
			"insert into edu.messages_real (message_id, from_user, ",
			"from_user_name, to_user, ",
			"to_user_name, message, ",
			"receive_tstp)",
			"values (#{message_id,jdbcType=NUMERIC}, #{from_user,jdbcType=NUMERIC}, ",
			"#{from_user_name,jdbcType=VARCHAR}, #{to_user,jdbcType=NUMERIC}, ",
			"#{to_user_name,jdbcType=VARCHAR}, #{message,jdbcType=VARCHAR}, ",
			"#{receive_tstp,jdbcType=TIMESTAMP})" })
	int insert(MessageReal record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table edu.messages_real
	 * @mbggenerated  Tue Feb 28 16:17:24 CST 2012
	 */
	int insertSelective(MessageReal record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table edu.messages_real
	 * @mbggenerated  Tue Feb 28 16:17:24 CST 2012
	 */
	List<MessageReal> selectByExample(MessageRealExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table edu.messages_real
	 * @mbggenerated  Tue Feb 28 16:17:24 CST 2012
	 */
	int updateByExampleSelective(@Param("record") MessageReal record,
			@Param("example") MessageRealExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table edu.messages_real
	 * @mbggenerated  Tue Feb 28 16:17:24 CST 2012
	 */
	int updateByExample(@Param("record") MessageReal record,
			@Param("example") MessageRealExample example);
}