package com.brightedu.dao.edu;

import com.brightedu.model.edu.PoliticalStatus;
import com.brightedu.model.edu.PoliticalStatusExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface PoliticalStatusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.sd_political_status
     *
     * @mbggenerated Sun Feb 12 11:48:59 CST 2012
     */
    int countByExample(PoliticalStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.sd_political_status
     *
     * @mbggenerated Sun Feb 12 11:48:59 CST 2012
     */
    int deleteByExample(PoliticalStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.sd_political_status
     *
     * @mbggenerated Sun Feb 12 11:48:59 CST 2012
     */
    @Delete({
        "delete from edu.sd_political_status",
        "where pol_id = #{pol_id,jdbcType=NUMERIC}"
    })
    int deleteByPrimaryKey(Integer pol_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.sd_political_status
     *
     * @mbggenerated Sun Feb 12 11:48:59 CST 2012
     */
    @Insert({
        "insert into edu.sd_political_status (pol_id, pol_name)",
        "values (#{pol_id,jdbcType=NUMERIC}, #{pol_name,jdbcType=VARCHAR})"
    })
    int insert(PoliticalStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.sd_political_status
     *
     * @mbggenerated Sun Feb 12 11:48:59 CST 2012
     */
    int insertSelective(PoliticalStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.sd_political_status
     *
     * @mbggenerated Sun Feb 12 11:48:59 CST 2012
     */
    List<PoliticalStatus> selectByExample(PoliticalStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.sd_political_status
     *
     * @mbggenerated Sun Feb 12 11:48:59 CST 2012
     */
    @Select({
        "select",
        "pol_id, pol_name",
        "from edu.sd_political_status",
        "where pol_id = #{pol_id,jdbcType=NUMERIC}"
    })
    @ResultMap("BaseResultMap")
    PoliticalStatus selectByPrimaryKey(Integer pol_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.sd_political_status
     *
     * @mbggenerated Sun Feb 12 11:48:59 CST 2012
     */
    int updateByExampleSelective(@Param("record") PoliticalStatus record, @Param("example") PoliticalStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.sd_political_status
     *
     * @mbggenerated Sun Feb 12 11:48:59 CST 2012
     */
    int updateByExample(@Param("record") PoliticalStatus record, @Param("example") PoliticalStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.sd_political_status
     *
     * @mbggenerated Sun Feb 12 11:48:59 CST 2012
     */
    int updateByPrimaryKeySelective(PoliticalStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.sd_political_status
     *
     * @mbggenerated Sun Feb 12 11:48:59 CST 2012
     */
    @Update({
        "update edu.sd_political_status",
        "set pol_name = #{pol_name,jdbcType=VARCHAR}",
        "where pol_id = #{pol_id,jdbcType=NUMERIC}"
    })
    int updateByPrimaryKey(PoliticalStatus record);
}