package com.brightedu.dao.edu;

import com.brightedu.model.edu.RecruitPlan;
import com.brightedu.model.edu.RecruitPlanExample;
import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;

public interface RecruitPlanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.recruit_plan_view
     *
     * @mbggenerated Fri Feb 17 12:34:17 CST 2012
     */
    int countByExample(RecruitPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.recruit_plan_view
     *
     * @mbggenerated Fri Feb 17 12:34:17 CST 2012
     */
    int deleteByExample(RecruitPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.recruit_plan_view
     *
     * @mbggenerated Fri Feb 17 12:34:17 CST 2012
     */
    @Insert({
        "insert into edu.recruit_plan_view (length_of_schooling, college_name, ",
        "batch_name, classified_name, ",
        "subject_name, batch_id)",
        "values (#{length_of_schooling,jdbcType=NUMERIC}, #{college_name,jdbcType=VARCHAR}, ",
        "#{batch_name,jdbcType=VARCHAR}, #{classified_name,jdbcType=VARCHAR}, ",
        "#{subject_name,jdbcType=VARCHAR}, #{batch_id,jdbcType=NUMERIC})"
    })
    int insert(RecruitPlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.recruit_plan_view
     *
     * @mbggenerated Fri Feb 17 12:34:17 CST 2012
     */
    int insertSelective(RecruitPlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.recruit_plan_view
     *
     * @mbggenerated Fri Feb 17 12:34:17 CST 2012
     */
    List<RecruitPlan> selectByExample(RecruitPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.recruit_plan_view
     *
     * @mbggenerated Fri Feb 17 12:34:17 CST 2012
     */
    int updateByExampleSelective(@Param("record") RecruitPlan record, @Param("example") RecruitPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.recruit_plan_view
     *
     * @mbggenerated Fri Feb 17 12:34:17 CST 2012
     */
    int updateByExample(@Param("record") RecruitPlan record, @Param("example") RecruitPlanExample example);
}