package com.brightedu.dao.edu;

import com.brightedu.model.edu.RightsCategoryFunctionExample;
import com.brightedu.model.edu.RightsCategoryFunctionKey;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;

public interface RightsCategoryFunctionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.rights_category_function
     *
     * @mbggenerated Fri Feb 17 17:28:53 CST 2012
     */
    int countByExample(RightsCategoryFunctionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.rights_category_function
     *
     * @mbggenerated Fri Feb 17 17:28:53 CST 2012
     */
    int deleteByExample(RightsCategoryFunctionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.rights_category_function
     *
     * @mbggenerated Fri Feb 17 17:28:53 CST 2012
     */
    @Delete({
        "delete from edu.rights_category_function",
        "where category_id = #{category_id,jdbcType=VARCHAR}",
          "and function_id = #{function_id,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(RightsCategoryFunctionKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.rights_category_function
     *
     * @mbggenerated Fri Feb 17 17:28:53 CST 2012
     */
    @Insert({
        "insert into edu.rights_category_function (category_id, function_id)",
        "values (#{category_id,jdbcType=VARCHAR}, #{function_id,jdbcType=VARCHAR})"
    })
    int insert(RightsCategoryFunctionKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.rights_category_function
     *
     * @mbggenerated Fri Feb 17 17:28:53 CST 2012
     */
    int insertSelective(RightsCategoryFunctionKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.rights_category_function
     *
     * @mbggenerated Fri Feb 17 17:28:53 CST 2012
     */
    List<RightsCategoryFunctionKey> selectByExample(RightsCategoryFunctionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.rights_category_function
     *
     * @mbggenerated Fri Feb 17 17:28:53 CST 2012
     */
    int updateByExampleSelective(@Param("record") RightsCategoryFunctionKey record, @Param("example") RightsCategoryFunctionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.rights_category_function
     *
     * @mbggenerated Fri Feb 17 17:28:53 CST 2012
     */
    int updateByExample(@Param("record") RightsCategoryFunctionKey record, @Param("example") RightsCategoryFunctionExample example);
}