package com.brightedu.dao.edu;

import com.brightedu.model.edu.RightsDefaultExample;
import com.brightedu.model.edu.RightsDefaultKey;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;

public interface RightsDefaultMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.rights_default
     *
     * @mbggenerated Fri Feb 17 17:28:53 CST 2012
     */
    int countByExample(RightsDefaultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.rights_default
     *
     * @mbggenerated Fri Feb 17 17:28:53 CST 2012
     */
    int deleteByExample(RightsDefaultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.rights_default
     *
     * @mbggenerated Fri Feb 17 17:28:53 CST 2012
     */
    @Delete({
        "delete from edu.rights_default",
        "where user_type_id = #{user_type_id,jdbcType=NUMERIC}",
          "and category_id = #{category_id,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(RightsDefaultKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.rights_default
     *
     * @mbggenerated Fri Feb 17 17:28:53 CST 2012
     */
    @Insert({
        "insert into edu.rights_default (user_type_id, category_id)",
        "values (#{user_type_id,jdbcType=NUMERIC}, #{category_id,jdbcType=VARCHAR})"
    })
    int insert(RightsDefaultKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.rights_default
     *
     * @mbggenerated Fri Feb 17 17:28:53 CST 2012
     */
    int insertSelective(RightsDefaultKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.rights_default
     *
     * @mbggenerated Fri Feb 17 17:28:53 CST 2012
     */
    List<RightsDefaultKey> selectByExample(RightsDefaultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.rights_default
     *
     * @mbggenerated Fri Feb 17 17:28:53 CST 2012
     */
    int updateByExampleSelective(@Param("record") RightsDefaultKey record, @Param("example") RightsDefaultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.rights_default
     *
     * @mbggenerated Fri Feb 17 17:28:53 CST 2012
     */
    int updateByExample(@Param("record") RightsDefaultKey record, @Param("example") RightsDefaultExample example);
}