package com.brightedu.dao.edu;

import com.brightedu.model.edu.School;
import com.brightedu.model.edu.SchoolExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface SchoolMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table edu.sd_school
	 * @mbggenerated  Sat Feb 11 02:04:14 CST 2012
	 */
	int countByExample(SchoolExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table edu.sd_school
	 * @mbggenerated  Sat Feb 11 02:04:14 CST 2012
	 */
	int deleteByExample(SchoolExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table edu.sd_school
	 * @mbggenerated  Sat Feb 11 02:04:14 CST 2012
	 */
	@Delete({ "delete from edu.sd_school",
			"where school_code = #{school_code,jdbcType=VARCHAR}" })
	int deleteByPrimaryKey(String school_code);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table edu.sd_school
	 * @mbggenerated  Sat Feb 11 02:04:14 CST 2012
	 */
	@Insert({ "insert into edu.sd_school (school_code, school_name)",
			"values (#{school_code,jdbcType=VARCHAR}, #{school_name,jdbcType=VARCHAR})" })
	int insert(School record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table edu.sd_school
	 * @mbggenerated  Sat Feb 11 02:04:14 CST 2012
	 */
	int insertSelective(School record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table edu.sd_school
	 * @mbggenerated  Sat Feb 11 02:04:14 CST 2012
	 */
	List<School> selectByExample(SchoolExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table edu.sd_school
	 * @mbggenerated  Sat Feb 11 02:04:14 CST 2012
	 */
	@Select({ "select", "school_code, school_name", "from edu.sd_school",
			"where school_code = #{school_code,jdbcType=VARCHAR}" })
	@ResultMap("BaseResultMap")
	School selectByPrimaryKey(String school_code);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table edu.sd_school
	 * @mbggenerated  Sat Feb 11 02:04:14 CST 2012
	 */
	int updateByExampleSelective(@Param("record") School record,
			@Param("example") SchoolExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table edu.sd_school
	 * @mbggenerated  Sat Feb 11 02:04:14 CST 2012
	 */
	int updateByExample(@Param("record") School record,
			@Param("example") SchoolExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table edu.sd_school
	 * @mbggenerated  Sat Feb 11 02:04:14 CST 2012
	 */
	int updateByPrimaryKeySelective(School record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table edu.sd_school
	 * @mbggenerated  Sat Feb 11 02:04:14 CST 2012
	 */
	@Update({ "update edu.sd_school",
			"set school_name = #{school_name,jdbcType=VARCHAR}",
			"where school_code = #{school_code,jdbcType=VARCHAR}" })
	int updateByPrimaryKey(School record);
}