package com.brightedu.dao.edu;

import com.brightedu.model.edu.StudentPicture;
import com.brightedu.model.edu.StudentPictureExample;
import com.brightedu.model.edu.StudentPictureKey;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface StudentPictureMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.student_pic
     *
     * @mbggenerated Sun Feb 12 12:25:52 CST 2012
     */
    int countByExample(StudentPictureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.student_pic
     *
     * @mbggenerated Sun Feb 12 12:25:52 CST 2012
     */
    int deleteByExample(StudentPictureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.student_pic
     *
     * @mbggenerated Sun Feb 12 12:25:52 CST 2012
     */
    @Delete({
        "delete from edu.student_pic",
        "where student_id = #{student_id,jdbcType=NUMERIC}",
          "and pic_type_id = #{pic_type_id,jdbcType=NUMERIC}"
    })
    int deleteByPrimaryKey(StudentPictureKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.student_pic
     *
     * @mbggenerated Sun Feb 12 12:25:52 CST 2012
     */
    @Insert({
        "insert into edu.student_pic (student_id, pic_type_id, ",
        "remark, register_date, ",
        "update_date, pic)",
        "values (#{student_id,jdbcType=NUMERIC}, #{pic_type_id,jdbcType=NUMERIC}, ",
        "#{remark,jdbcType=VARCHAR}, #{register_date,jdbcType=TIMESTAMP}, ",
        "#{update_date,jdbcType=TIMESTAMP}, #{pic,jdbcType=BINARY})"
    })
    int insert(StudentPicture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.student_pic
     *
     * @mbggenerated Sun Feb 12 12:25:52 CST 2012
     */
    int insertSelective(StudentPicture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.student_pic
     *
     * @mbggenerated Sun Feb 12 12:25:52 CST 2012
     */
    List<StudentPicture> selectByExampleWithBLOBs(StudentPictureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.student_pic
     *
     * @mbggenerated Sun Feb 12 12:25:52 CST 2012
     */
    List<StudentPicture> selectByExample(StudentPictureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.student_pic
     *
     * @mbggenerated Sun Feb 12 12:25:52 CST 2012
     */
    @Select({
        "select",
        "student_id, pic_type_id, remark, register_date, update_date, pic",
        "from edu.student_pic",
        "where student_id = #{student_id,jdbcType=NUMERIC}",
          "and pic_type_id = #{pic_type_id,jdbcType=NUMERIC}"
    })
    @ResultMap("ResultMapWithBLOBs")
    StudentPicture selectByPrimaryKey(StudentPictureKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.student_pic
     *
     * @mbggenerated Sun Feb 12 12:25:52 CST 2012
     */
    int updateByExampleSelective(@Param("record") StudentPicture record, @Param("example") StudentPictureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.student_pic
     *
     * @mbggenerated Sun Feb 12 12:25:52 CST 2012
     */
    int updateByExampleWithBLOBs(@Param("record") StudentPicture record, @Param("example") StudentPictureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.student_pic
     *
     * @mbggenerated Sun Feb 12 12:25:52 CST 2012
     */
    int updateByExample(@Param("record") StudentPicture record, @Param("example") StudentPictureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.student_pic
     *
     * @mbggenerated Sun Feb 12 12:25:52 CST 2012
     */
    int updateByPrimaryKeySelective(StudentPicture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.student_pic
     *
     * @mbggenerated Sun Feb 12 12:25:52 CST 2012
     */
    @Update({
        "update edu.student_pic",
        "set remark = #{remark,jdbcType=VARCHAR},",
          "register_date = #{register_date,jdbcType=TIMESTAMP},",
          "update_date = #{update_date,jdbcType=TIMESTAMP},",
          "pic = #{pic,jdbcType=BINARY}",
        "where student_id = #{student_id,jdbcType=NUMERIC}",
          "and pic_type_id = #{pic_type_id,jdbcType=NUMERIC}"
    })
    int updateByPrimaryKeyWithBLOBs(StudentPicture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.student_pic
     *
     * @mbggenerated Sun Feb 12 12:25:52 CST 2012
     */
    @Update({
        "update edu.student_pic",
        "set remark = #{remark,jdbcType=VARCHAR},",
          "register_date = #{register_date,jdbcType=TIMESTAMP},",
          "update_date = #{update_date,jdbcType=TIMESTAMP}",
        "where student_id = #{student_id,jdbcType=NUMERIC}",
          "and pic_type_id = #{pic_type_id,jdbcType=NUMERIC}"
    })
    int updateByPrimaryKey(StudentPicture record);
}