package com.brightedu.dao.edu;

import com.brightedu.model.edu.UserRights;
import com.brightedu.model.edu.UserRightsExample;
import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;

public interface UserRightsMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table edu.userrights_view
	 * @mbggenerated  Tue Feb 21 12:16:24 CST 2012
	 */
	int countByExample(UserRightsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table edu.userrights_view
	 * @mbggenerated  Tue Feb 21 12:16:24 CST 2012
	 */
	int deleteByExample(UserRightsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table edu.userrights_view
	 * @mbggenerated  Tue Feb 21 12:16:24 CST 2012
	 */
	@Insert({
			"insert into edu.userrights_view (category_id, function_id, ",
			"category_name, function_name, ",
			"isset, user_id)",
			"values (#{category_id,jdbcType=VARCHAR}, #{function_id,jdbcType=VARCHAR}, ",
			"#{category_name,jdbcType=VARCHAR}, #{function_name,jdbcType=VARCHAR}, ",
			"#{isset,jdbcType=VARCHAR}, #{user_id,jdbcType=NUMERIC})" })
	int insert(UserRights record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table edu.userrights_view
	 * @mbggenerated  Tue Feb 21 12:16:24 CST 2012
	 */
	int insertSelective(UserRights record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table edu.userrights_view
	 * @mbggenerated  Tue Feb 21 12:16:24 CST 2012
	 */
	List<UserRights> selectByExample(UserRightsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table edu.userrights_view
	 * @mbggenerated  Tue Feb 21 12:16:24 CST 2012
	 */
	int updateByExampleSelective(@Param("record") UserRights record,
			@Param("example") UserRightsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table edu.userrights_view
	 * @mbggenerated  Tue Feb 21 12:16:24 CST 2012
	 */
	int updateByExample(@Param("record") UserRights record,
			@Param("example") UserRightsExample example);
}