package com.brightedu.dao.edu;

import com.brightedu.model.edu.UserRightsEffective;
import com.brightedu.model.edu.UserRightsEffectiveExample;
import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;

public interface UserRightsEffectiveMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.userrights_effective
     *
     * @mbggenerated Tue Feb 21 12:16:24 CST 2012
     */
    int countByExample(UserRightsEffectiveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.userrights_effective
     *
     * @mbggenerated Tue Feb 21 12:16:24 CST 2012
     */
    int deleteByExample(UserRightsEffectiveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.userrights_effective
     *
     * @mbggenerated Tue Feb 21 12:16:24 CST 2012
     */
    @Insert({
        "insert into edu.userrights_effective (category_id, function_id, ",
        "category_name, function_name, ",
        "user_id)",
        "values (#{category_id,jdbcType=VARCHAR}, #{function_id,jdbcType=VARCHAR}, ",
        "#{category_name,jdbcType=VARCHAR}, #{function_name,jdbcType=VARCHAR}, ",
        "#{user_id,jdbcType=NUMERIC})"
    })
    int insert(UserRightsEffective record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.userrights_effective
     *
     * @mbggenerated Tue Feb 21 12:16:24 CST 2012
     */
    int insertSelective(UserRightsEffective record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.userrights_effective
     *
     * @mbggenerated Tue Feb 21 12:16:24 CST 2012
     */
    List<UserRightsEffective> selectByExample(UserRightsEffectiveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.userrights_effective
     *
     * @mbggenerated Tue Feb 21 12:16:24 CST 2012
     */
    int updateByExampleSelective(@Param("record") UserRightsEffective record, @Param("example") UserRightsEffectiveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu.userrights_effective
     *
     * @mbggenerated Tue Feb 21 12:16:24 CST 2012
     */
    int updateByExample(@Param("record") UserRightsEffective record, @Param("example") UserRightsEffectiveExample example);
}