package com.brightedu.model.edu;

import java.io.Serializable;
import java.math.BigDecimal;

public class AgentReturn  implements Serializable{

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column edu.agent_return.ag_return_id
	 * @mbggenerated  Thu Feb 02 16:54:43 CST 2012
	 */
	private Integer ag_return_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column edu.agent_return.agent_id
	 * @mbggenerated  Thu Feb 02 16:54:43 CST 2012
	 */
	private Integer agent_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column edu.agent_return.college_id
	 * @mbggenerated  Thu Feb 02 16:54:43 CST 2012
	 */
	private Integer college_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column edu.agent_return.batch_id
	 * @mbggenerated  Thu Feb 02 16:54:43 CST 2012
	 */
	private Integer batch_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column edu.agent_return.head_count
	 * @mbggenerated  Thu Feb 02 16:54:43 CST 2012
	 */
	private Long head_count;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column edu.agent_return.return_percent
	 * @mbggenerated  Thu Feb 02 16:54:43 CST 2012
	 */
	private BigDecimal return_percent;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column edu.agent_return.ag_return_id
	 * @return  the value of edu.agent_return.ag_return_id
	 * @mbggenerated  Thu Feb 02 16:54:43 CST 2012
	 */
	public Integer getAg_return_id() {
		return ag_return_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column edu.agent_return.ag_return_id
	 * @param ag_return_id  the value for edu.agent_return.ag_return_id
	 * @mbggenerated  Thu Feb 02 16:54:43 CST 2012
	 */
	public void setAg_return_id(Integer ag_return_id) {
		this.ag_return_id = ag_return_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column edu.agent_return.agent_id
	 * @return  the value of edu.agent_return.agent_id
	 * @mbggenerated  Thu Feb 02 16:54:43 CST 2012
	 */
	public Integer getAgent_id() {
		return agent_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column edu.agent_return.agent_id
	 * @param agent_id  the value for edu.agent_return.agent_id
	 * @mbggenerated  Thu Feb 02 16:54:43 CST 2012
	 */
	public void setAgent_id(Integer agent_id) {
		this.agent_id = agent_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column edu.agent_return.college_id
	 * @return  the value of edu.agent_return.college_id
	 * @mbggenerated  Thu Feb 02 16:54:43 CST 2012
	 */
	public Integer getCollege_id() {
		return college_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column edu.agent_return.college_id
	 * @param college_id  the value for edu.agent_return.college_id
	 * @mbggenerated  Thu Feb 02 16:54:43 CST 2012
	 */
	public void setCollege_id(Integer college_id) {
		this.college_id = college_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column edu.agent_return.batch_id
	 * @return  the value of edu.agent_return.batch_id
	 * @mbggenerated  Thu Feb 02 16:54:43 CST 2012
	 */
	public Integer getBatch_id() {
		return batch_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column edu.agent_return.batch_id
	 * @param batch_id  the value for edu.agent_return.batch_id
	 * @mbggenerated  Thu Feb 02 16:54:43 CST 2012
	 */
	public void setBatch_id(Integer batch_id) {
		this.batch_id = batch_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column edu.agent_return.head_count
	 * @return  the value of edu.agent_return.head_count
	 * @mbggenerated  Thu Feb 02 16:54:43 CST 2012
	 */
	public Long getHead_count() {
		return head_count;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column edu.agent_return.head_count
	 * @param head_count  the value for edu.agent_return.head_count
	 * @mbggenerated  Thu Feb 02 16:54:43 CST 2012
	 */
	public void setHead_count(Long head_count) {
		this.head_count = head_count;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column edu.agent_return.return_percent
	 * @return  the value of edu.agent_return.return_percent
	 * @mbggenerated  Thu Feb 02 16:54:43 CST 2012
	 */
	public BigDecimal getReturn_percent() {
		return return_percent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column edu.agent_return.return_percent
	 * @param return_percent  the value for edu.agent_return.return_percent
	 * @mbggenerated  Thu Feb 02 16:54:43 CST 2012
	 */
	public void setReturn_percent(BigDecimal return_percent) {
		this.return_percent = return_percent;
	}
}