package com.brightedu.model.edu;

import com.brightedu.client.ds.Page;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class AnnouncementExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table edu.announcement
	 * @mbggenerated  Wed Feb 29 12:07:54 CST 2012
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table edu.announcement
	 * @mbggenerated  Wed Feb 29 12:07:54 CST 2012
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table edu.announcement
	 * @mbggenerated  Wed Feb 29 12:07:54 CST 2012
	 */
	protected List<Criteria> oredCriteria;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table edu.announcement
	 * @mbggenerated  Wed Feb 29 12:07:54 CST 2012
	 */
	protected Page page;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table edu.announcement
	 * @mbggenerated  Wed Feb 29 12:07:54 CST 2012
	 */
	public AnnouncementExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table edu.announcement
	 * @mbggenerated  Wed Feb 29 12:07:54 CST 2012
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table edu.announcement
	 * @mbggenerated  Wed Feb 29 12:07:54 CST 2012
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table edu.announcement
	 * @mbggenerated  Wed Feb 29 12:07:54 CST 2012
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table edu.announcement
	 * @mbggenerated  Wed Feb 29 12:07:54 CST 2012
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table edu.announcement
	 * @mbggenerated  Wed Feb 29 12:07:54 CST 2012
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table edu.announcement
	 * @mbggenerated  Wed Feb 29 12:07:54 CST 2012
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table edu.announcement
	 * @mbggenerated  Wed Feb 29 12:07:54 CST 2012
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table edu.announcement
	 * @mbggenerated  Wed Feb 29 12:07:54 CST 2012
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table edu.announcement
	 * @mbggenerated  Wed Feb 29 12:07:54 CST 2012
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table edu.announcement
	 * @mbggenerated  Wed Feb 29 12:07:54 CST 2012
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table edu.announcement
	 * @mbggenerated  Wed Feb 29 12:07:54 CST 2012
	 */
	public void setPage(Page page) {
		this.page = page;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table edu.announcement
	 * @mbggenerated  Wed Feb 29 12:07:54 CST 2012
	 */
	public Page getPage() {
		return page;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table edu.announcement
	 * @mbggenerated  Wed Feb 29 12:07:54 CST 2012
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andAnn_idIsNull() {
			addCriterion("ann_id is null");
			return (Criteria) this;
		}

		public Criteria andAnn_idIsNotNull() {
			addCriterion("ann_id is not null");
			return (Criteria) this;
		}

		public Criteria andAnn_idEqualTo(Integer value) {
			addCriterion("ann_id =", value, "ann_id");
			return (Criteria) this;
		}

		public Criteria andAnn_idNotEqualTo(Integer value) {
			addCriterion("ann_id <>", value, "ann_id");
			return (Criteria) this;
		}

		public Criteria andAnn_idGreaterThan(Integer value) {
			addCriterion("ann_id >", value, "ann_id");
			return (Criteria) this;
		}

		public Criteria andAnn_idGreaterThanOrEqualTo(Integer value) {
			addCriterion("ann_id >=", value, "ann_id");
			return (Criteria) this;
		}

		public Criteria andAnn_idLessThan(Integer value) {
			addCriterion("ann_id <", value, "ann_id");
			return (Criteria) this;
		}

		public Criteria andAnn_idLessThanOrEqualTo(Integer value) {
			addCriterion("ann_id <=", value, "ann_id");
			return (Criteria) this;
		}

		public Criteria andAnn_idIn(List<Integer> values) {
			addCriterion("ann_id in", values, "ann_id");
			return (Criteria) this;
		}

		public Criteria andAnn_idNotIn(List<Integer> values) {
			addCriterion("ann_id not in", values, "ann_id");
			return (Criteria) this;
		}

		public Criteria andAnn_idBetween(Integer value1, Integer value2) {
			addCriterion("ann_id between", value1, value2, "ann_id");
			return (Criteria) this;
		}

		public Criteria andAnn_idNotBetween(Integer value1, Integer value2) {
			addCriterion("ann_id not between", value1, value2, "ann_id");
			return (Criteria) this;
		}

		public Criteria andAnn_titleIsNull() {
			addCriterion("ann_title is null");
			return (Criteria) this;
		}

		public Criteria andAnn_titleIsNotNull() {
			addCriterion("ann_title is not null");
			return (Criteria) this;
		}

		public Criteria andAnn_titleEqualTo(String value) {
			addCriterion("ann_title =", value, "ann_title");
			return (Criteria) this;
		}

		public Criteria andAnn_titleNotEqualTo(String value) {
			addCriterion("ann_title <>", value, "ann_title");
			return (Criteria) this;
		}

		public Criteria andAnn_titleGreaterThan(String value) {
			addCriterion("ann_title >", value, "ann_title");
			return (Criteria) this;
		}

		public Criteria andAnn_titleGreaterThanOrEqualTo(String value) {
			addCriterion("ann_title >=", value, "ann_title");
			return (Criteria) this;
		}

		public Criteria andAnn_titleLessThan(String value) {
			addCriterion("ann_title <", value, "ann_title");
			return (Criteria) this;
		}

		public Criteria andAnn_titleLessThanOrEqualTo(String value) {
			addCriterion("ann_title <=", value, "ann_title");
			return (Criteria) this;
		}

		public Criteria andAnn_titleLike(String value) {
			addCriterion("ann_title like", value, "ann_title");
			return (Criteria) this;
		}

		public Criteria andAnn_titleNotLike(String value) {
			addCriterion("ann_title not like", value, "ann_title");
			return (Criteria) this;
		}

		public Criteria andAnn_titleIn(List<String> values) {
			addCriterion("ann_title in", values, "ann_title");
			return (Criteria) this;
		}

		public Criteria andAnn_titleNotIn(List<String> values) {
			addCriterion("ann_title not in", values, "ann_title");
			return (Criteria) this;
		}

		public Criteria andAnn_titleBetween(String value1, String value2) {
			addCriterion("ann_title between", value1, value2, "ann_title");
			return (Criteria) this;
		}

		public Criteria andAnn_titleNotBetween(String value1, String value2) {
			addCriterion("ann_title not between", value1, value2, "ann_title");
			return (Criteria) this;
		}

		public Criteria andAnn_bodyIsNull() {
			addCriterion("ann_body is null");
			return (Criteria) this;
		}

		public Criteria andAnn_bodyIsNotNull() {
			addCriterion("ann_body is not null");
			return (Criteria) this;
		}

		public Criteria andAnn_bodyEqualTo(String value) {
			addCriterion("ann_body =", value, "ann_body");
			return (Criteria) this;
		}

		public Criteria andAnn_bodyNotEqualTo(String value) {
			addCriterion("ann_body <>", value, "ann_body");
			return (Criteria) this;
		}

		public Criteria andAnn_bodyGreaterThan(String value) {
			addCriterion("ann_body >", value, "ann_body");
			return (Criteria) this;
		}

		public Criteria andAnn_bodyGreaterThanOrEqualTo(String value) {
			addCriterion("ann_body >=", value, "ann_body");
			return (Criteria) this;
		}

		public Criteria andAnn_bodyLessThan(String value) {
			addCriterion("ann_body <", value, "ann_body");
			return (Criteria) this;
		}

		public Criteria andAnn_bodyLessThanOrEqualTo(String value) {
			addCriterion("ann_body <=", value, "ann_body");
			return (Criteria) this;
		}

		public Criteria andAnn_bodyLike(String value) {
			addCriterion("ann_body like", value, "ann_body");
			return (Criteria) this;
		}

		public Criteria andAnn_bodyNotLike(String value) {
			addCriterion("ann_body not like", value, "ann_body");
			return (Criteria) this;
		}

		public Criteria andAnn_bodyIn(List<String> values) {
			addCriterion("ann_body in", values, "ann_body");
			return (Criteria) this;
		}

		public Criteria andAnn_bodyNotIn(List<String> values) {
			addCriterion("ann_body not in", values, "ann_body");
			return (Criteria) this;
		}

		public Criteria andAnn_bodyBetween(String value1, String value2) {
			addCriterion("ann_body between", value1, value2, "ann_body");
			return (Criteria) this;
		}

		public Criteria andAnn_bodyNotBetween(String value1, String value2) {
			addCriterion("ann_body not between", value1, value2, "ann_body");
			return (Criteria) this;
		}

		public Criteria andReg_dateIsNull() {
			addCriterion("reg_date is null");
			return (Criteria) this;
		}

		public Criteria andReg_dateIsNotNull() {
			addCriterion("reg_date is not null");
			return (Criteria) this;
		}

		public Criteria andReg_dateEqualTo(Date value) {
			addCriterion("reg_date =", value, "reg_date");
			return (Criteria) this;
		}

		public Criteria andReg_dateNotEqualTo(Date value) {
			addCriterion("reg_date <>", value, "reg_date");
			return (Criteria) this;
		}

		public Criteria andReg_dateGreaterThan(Date value) {
			addCriterion("reg_date >", value, "reg_date");
			return (Criteria) this;
		}

		public Criteria andReg_dateGreaterThanOrEqualTo(Date value) {
			addCriterion("reg_date >=", value, "reg_date");
			return (Criteria) this;
		}

		public Criteria andReg_dateLessThan(Date value) {
			addCriterion("reg_date <", value, "reg_date");
			return (Criteria) this;
		}

		public Criteria andReg_dateLessThanOrEqualTo(Date value) {
			addCriterion("reg_date <=", value, "reg_date");
			return (Criteria) this;
		}

		public Criteria andReg_dateIn(List<Date> values) {
			addCriterion("reg_date in", values, "reg_date");
			return (Criteria) this;
		}

		public Criteria andReg_dateNotIn(List<Date> values) {
			addCriterion("reg_date not in", values, "reg_date");
			return (Criteria) this;
		}

		public Criteria andReg_dateBetween(Date value1, Date value2) {
			addCriterion("reg_date between", value1, value2, "reg_date");
			return (Criteria) this;
		}

		public Criteria andReg_dateNotBetween(Date value1, Date value2) {
			addCriterion("reg_date not between", value1, value2, "reg_date");
			return (Criteria) this;
		}

		public Criteria andCreated_byIsNull() {
			addCriterion("created_by is null");
			return (Criteria) this;
		}

		public Criteria andCreated_byIsNotNull() {
			addCriterion("created_by is not null");
			return (Criteria) this;
		}

		public Criteria andCreated_byEqualTo(Integer value) {
			addCriterion("created_by =", value, "created_by");
			return (Criteria) this;
		}

		public Criteria andCreated_byNotEqualTo(Integer value) {
			addCriterion("created_by <>", value, "created_by");
			return (Criteria) this;
		}

		public Criteria andCreated_byGreaterThan(Integer value) {
			addCriterion("created_by >", value, "created_by");
			return (Criteria) this;
		}

		public Criteria andCreated_byGreaterThanOrEqualTo(Integer value) {
			addCriterion("created_by >=", value, "created_by");
			return (Criteria) this;
		}

		public Criteria andCreated_byLessThan(Integer value) {
			addCriterion("created_by <", value, "created_by");
			return (Criteria) this;
		}

		public Criteria andCreated_byLessThanOrEqualTo(Integer value) {
			addCriterion("created_by <=", value, "created_by");
			return (Criteria) this;
		}

		public Criteria andCreated_byIn(List<Integer> values) {
			addCriterion("created_by in", values, "created_by");
			return (Criteria) this;
		}

		public Criteria andCreated_byNotIn(List<Integer> values) {
			addCriterion("created_by not in", values, "created_by");
			return (Criteria) this;
		}

		public Criteria andCreated_byBetween(Integer value1, Integer value2) {
			addCriterion("created_by between", value1, value2, "created_by");
			return (Criteria) this;
		}

		public Criteria andCreated_byNotBetween(Integer value1, Integer value2) {
			addCriterion("created_by not between", value1, value2, "created_by");
			return (Criteria) this;
		}

		public Criteria andLast_edited_byIsNull() {
			addCriterion("last_edited_by is null");
			return (Criteria) this;
		}

		public Criteria andLast_edited_byIsNotNull() {
			addCriterion("last_edited_by is not null");
			return (Criteria) this;
		}

		public Criteria andLast_edited_byEqualTo(Integer value) {
			addCriterion("last_edited_by =", value, "last_edited_by");
			return (Criteria) this;
		}

		public Criteria andLast_edited_byNotEqualTo(Integer value) {
			addCriterion("last_edited_by <>", value, "last_edited_by");
			return (Criteria) this;
		}

		public Criteria andLast_edited_byGreaterThan(Integer value) {
			addCriterion("last_edited_by >", value, "last_edited_by");
			return (Criteria) this;
		}

		public Criteria andLast_edited_byGreaterThanOrEqualTo(Integer value) {
			addCriterion("last_edited_by >=", value, "last_edited_by");
			return (Criteria) this;
		}

		public Criteria andLast_edited_byLessThan(Integer value) {
			addCriterion("last_edited_by <", value, "last_edited_by");
			return (Criteria) this;
		}

		public Criteria andLast_edited_byLessThanOrEqualTo(Integer value) {
			addCriterion("last_edited_by <=", value, "last_edited_by");
			return (Criteria) this;
		}

		public Criteria andLast_edited_byIn(List<Integer> values) {
			addCriterion("last_edited_by in", values, "last_edited_by");
			return (Criteria) this;
		}

		public Criteria andLast_edited_byNotIn(List<Integer> values) {
			addCriterion("last_edited_by not in", values, "last_edited_by");
			return (Criteria) this;
		}

		public Criteria andLast_edited_byBetween(Integer value1, Integer value2) {
			addCriterion("last_edited_by between", value1, value2,
					"last_edited_by");
			return (Criteria) this;
		}

		public Criteria andLast_edited_byNotBetween(Integer value1,
				Integer value2) {
			addCriterion("last_edited_by not between", value1, value2,
					"last_edited_by");
			return (Criteria) this;
		}

		public Criteria andUpdate_timeIsNull() {
			addCriterion("update_time is null");
			return (Criteria) this;
		}

		public Criteria andUpdate_timeIsNotNull() {
			addCriterion("update_time is not null");
			return (Criteria) this;
		}

		public Criteria andUpdate_timeEqualTo(Date value) {
			addCriterion("update_time =", value, "update_time");
			return (Criteria) this;
		}

		public Criteria andUpdate_timeNotEqualTo(Date value) {
			addCriterion("update_time <>", value, "update_time");
			return (Criteria) this;
		}

		public Criteria andUpdate_timeGreaterThan(Date value) {
			addCriterion("update_time >", value, "update_time");
			return (Criteria) this;
		}

		public Criteria andUpdate_timeGreaterThanOrEqualTo(Date value) {
			addCriterion("update_time >=", value, "update_time");
			return (Criteria) this;
		}

		public Criteria andUpdate_timeLessThan(Date value) {
			addCriterion("update_time <", value, "update_time");
			return (Criteria) this;
		}

		public Criteria andUpdate_timeLessThanOrEqualTo(Date value) {
			addCriterion("update_time <=", value, "update_time");
			return (Criteria) this;
		}

		public Criteria andUpdate_timeIn(List<Date> values) {
			addCriterion("update_time in", values, "update_time");
			return (Criteria) this;
		}

		public Criteria andUpdate_timeNotIn(List<Date> values) {
			addCriterion("update_time not in", values, "update_time");
			return (Criteria) this;
		}

		public Criteria andUpdate_timeBetween(Date value1, Date value2) {
			addCriterion("update_time between", value1, value2, "update_time");
			return (Criteria) this;
		}

		public Criteria andUpdate_timeNotBetween(Date value1, Date value2) {
			addCriterion("update_time not between", value1, value2,
					"update_time");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table edu.announcement
	 * @mbggenerated  Wed Feb 29 12:07:54 CST 2012
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table edu.announcement
     *
     * @mbggenerated do_not_delete_during_merge Wed Feb 29 11:48:16 CST 2012
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}