package com.brightedu.model.edu;

import java.io.Serializable;
import java.util.Date;

public class BatchIndex implements Serializable{

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column edu.batch_index.batch_id
	 * @mbggenerated  Thu Feb 02 16:54:43 CST 2012
	 */
	private Integer batch_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column edu.batch_index.batch_name
	 * @mbggenerated  Thu Feb 02 16:54:43 CST 2012
	 */
	private String batch_name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column edu.batch_index.register_date
	 * @mbggenerated  Thu Feb 02 16:54:43 CST 2012
	 */
	private Date register_date;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column edu.batch_index.batch_id
	 * @return  the value of edu.batch_index.batch_id
	 * @mbggenerated  Thu Feb 02 16:54:43 CST 2012
	 */
	public Integer getBatch_id() {
		return batch_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column edu.batch_index.batch_id
	 * @param batch_id  the value for edu.batch_index.batch_id
	 * @mbggenerated  Thu Feb 02 16:54:43 CST 2012
	 */
	public void setBatch_id(Integer batch_id) {
		this.batch_id = batch_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column edu.batch_index.batch_name
	 * @return  the value of edu.batch_index.batch_name
	 * @mbggenerated  Thu Feb 02 16:54:43 CST 2012
	 */
	public String getBatch_name() {
		return batch_name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column edu.batch_index.batch_name
	 * @param batch_name  the value for edu.batch_index.batch_name
	 * @mbggenerated  Thu Feb 02 16:54:43 CST 2012
	 */
	public void setBatch_name(String batch_name) {
		this.batch_name = batch_name == null ? null : batch_name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column edu.batch_index.register_date
	 * @return  the value of edu.batch_index.register_date
	 * @mbggenerated  Thu Feb 02 16:54:43 CST 2012
	 */
	public Date getRegister_date() {
		return register_date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column edu.batch_index.register_date
	 * @param register_date  the value for edu.batch_index.register_date
	 * @mbggenerated  Thu Feb 02 16:54:43 CST 2012
	 */
	public void setRegister_date(Date register_date) {
		this.register_date = register_date;
	}
}