package com.brightedu.model.edu;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class ChargeAdmin  implements Serializable{

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column edu.charge_admin.charge_id
	 * @mbggenerated  Sun Feb 26 19:53:20 CST 2012
	 */
	private Integer charge_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column edu.charge_admin.student_id
	 * @mbggenerated  Sun Feb 26 19:53:20 CST 2012
	 */
	private Integer student_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column edu.charge_admin.fee_id
	 * @mbggenerated  Sun Feb 26 19:53:20 CST 2012
	 */
	private Integer fee_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column edu.charge_admin.charge_type_id
	 * @mbggenerated  Sun Feb 26 19:53:20 CST 2012
	 */
	private Integer charge_type_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column edu.charge_admin.bank_code
	 * @mbggenerated  Sun Feb 26 19:53:20 CST 2012
	 */
	private String bank_code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column edu.charge_admin.amount_flag
	 * @mbggenerated  Sun Feb 26 19:53:20 CST 2012
	 */
	private Boolean amount_flag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column edu.charge_admin.amount
	 * @mbggenerated  Sun Feb 26 19:53:20 CST 2012
	 */
	private BigDecimal amount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column edu.charge_admin.charge_time
	 * @mbggenerated  Sun Feb 26 19:53:20 CST 2012
	 */
	private Date charge_time;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column edu.charge_admin.remark
	 * @mbggenerated  Sun Feb 26 19:53:20 CST 2012
	 */
	private String remark;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column edu.charge_admin.due_date
	 * @mbggenerated  Sun Feb 26 19:53:20 CST 2012
	 */
	private Date due_date;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column edu.charge_admin.agent_return_id
	 * @mbggenerated  Sun Feb 26 19:53:20 CST 2012
	 */
	private Integer agent_return_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table edu.charge_admin
	 * @mbggenerated  Sun Feb 26 19:53:20 CST 2012
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column edu.charge_admin.charge_id
	 * @return  the value of edu.charge_admin.charge_id
	 * @mbggenerated  Sun Feb 26 19:53:20 CST 2012
	 */
	public Integer getCharge_id() {
		return charge_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column edu.charge_admin.charge_id
	 * @param charge_id  the value for edu.charge_admin.charge_id
	 * @mbggenerated  Sun Feb 26 19:53:20 CST 2012
	 */
	public void setCharge_id(Integer charge_id) {
		this.charge_id = charge_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column edu.charge_admin.student_id
	 * @return  the value of edu.charge_admin.student_id
	 * @mbggenerated  Sun Feb 26 19:53:20 CST 2012
	 */
	public Integer getStudent_id() {
		return student_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column edu.charge_admin.student_id
	 * @param student_id  the value for edu.charge_admin.student_id
	 * @mbggenerated  Sun Feb 26 19:53:20 CST 2012
	 */
	public void setStudent_id(Integer student_id) {
		this.student_id = student_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column edu.charge_admin.fee_id
	 * @return  the value of edu.charge_admin.fee_id
	 * @mbggenerated  Sun Feb 26 19:53:20 CST 2012
	 */
	public Integer getFee_id() {
		return fee_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column edu.charge_admin.fee_id
	 * @param fee_id  the value for edu.charge_admin.fee_id
	 * @mbggenerated  Sun Feb 26 19:53:20 CST 2012
	 */
	public void setFee_id(Integer fee_id) {
		this.fee_id = fee_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column edu.charge_admin.charge_type_id
	 * @return  the value of edu.charge_admin.charge_type_id
	 * @mbggenerated  Sun Feb 26 19:53:20 CST 2012
	 */
	public Integer getCharge_type_id() {
		return charge_type_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column edu.charge_admin.charge_type_id
	 * @param charge_type_id  the value for edu.charge_admin.charge_type_id
	 * @mbggenerated  Sun Feb 26 19:53:20 CST 2012
	 */
	public void setCharge_type_id(Integer charge_type_id) {
		this.charge_type_id = charge_type_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column edu.charge_admin.bank_code
	 * @return  the value of edu.charge_admin.bank_code
	 * @mbggenerated  Sun Feb 26 19:53:20 CST 2012
	 */
	public String getBank_code() {
		return bank_code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column edu.charge_admin.bank_code
	 * @param bank_code  the value for edu.charge_admin.bank_code
	 * @mbggenerated  Sun Feb 26 19:53:20 CST 2012
	 */
	public void setBank_code(String bank_code) {
		this.bank_code = bank_code == null ? null : bank_code.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column edu.charge_admin.amount_flag
	 * @return  the value of edu.charge_admin.amount_flag
	 * @mbggenerated  Sun Feb 26 19:53:20 CST 2012
	 */
	public Boolean getAmount_flag() {
		return amount_flag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column edu.charge_admin.amount_flag
	 * @param amount_flag  the value for edu.charge_admin.amount_flag
	 * @mbggenerated  Sun Feb 26 19:53:20 CST 2012
	 */
	public void setAmount_flag(Boolean amount_flag) {
		this.amount_flag = amount_flag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column edu.charge_admin.amount
	 * @return  the value of edu.charge_admin.amount
	 * @mbggenerated  Sun Feb 26 19:53:20 CST 2012
	 */
	public BigDecimal getAmount() {
		return amount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column edu.charge_admin.amount
	 * @param amount  the value for edu.charge_admin.amount
	 * @mbggenerated  Sun Feb 26 19:53:20 CST 2012
	 */
	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column edu.charge_admin.charge_time
	 * @return  the value of edu.charge_admin.charge_time
	 * @mbggenerated  Sun Feb 26 19:53:20 CST 2012
	 */
	public Date getCharge_time() {
		return charge_time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column edu.charge_admin.charge_time
	 * @param charge_time  the value for edu.charge_admin.charge_time
	 * @mbggenerated  Sun Feb 26 19:53:20 CST 2012
	 */
	public void setCharge_time(Date charge_time) {
		this.charge_time = charge_time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column edu.charge_admin.remark
	 * @return  the value of edu.charge_admin.remark
	 * @mbggenerated  Sun Feb 26 19:53:20 CST 2012
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column edu.charge_admin.remark
	 * @param remark  the value for edu.charge_admin.remark
	 * @mbggenerated  Sun Feb 26 19:53:20 CST 2012
	 */
	public void setRemark(String remark) {
		this.remark = remark == null ? null : remark.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column edu.charge_admin.due_date
	 * @return  the value of edu.charge_admin.due_date
	 * @mbggenerated  Sun Feb 26 19:53:20 CST 2012
	 */
	public Date getDue_date() {
		return due_date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column edu.charge_admin.due_date
	 * @param due_date  the value for edu.charge_admin.due_date
	 * @mbggenerated  Sun Feb 26 19:53:20 CST 2012
	 */
	public void setDue_date(Date due_date) {
		this.due_date = due_date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column edu.charge_admin.agent_return_id
	 * @return  the value of edu.charge_admin.agent_return_id
	 * @mbggenerated  Sun Feb 26 19:53:20 CST 2012
	 */
	public Integer getAgent_return_id() {
		return agent_return_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column edu.charge_admin.agent_return_id
	 * @param agent_return_id  the value for edu.charge_admin.agent_return_id
	 * @mbggenerated  Sun Feb 26 19:53:20 CST 2012
	 */
	public void setAgent_return_id(Integer agent_return_id) {
		this.agent_return_id = agent_return_id;
	}
}