package com.brightedu.model.edu;

public class EntranceCostKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edu.entrance_cost.college_id
     *
     * @mbggenerated Sun Jan 15 18:52:28 CST 2012
     */
    private Integer college_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edu.entrance_cost.batch_id
     *
     * @mbggenerated Sun Jan 15 18:52:28 CST 2012
     */
    private Integer batch_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edu.entrance_cost.subject_id
     *
     * @mbggenerated Sun Jan 15 18:52:28 CST 2012
     */
    private Integer subject_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edu.entrance_cost.college_id
     *
     * @return the value of edu.entrance_cost.college_id
     *
     * @mbggenerated Sun Jan 15 18:52:28 CST 2012
     */
    public Integer getCollege_id() {
        return college_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edu.entrance_cost.college_id
     *
     * @param college_id the value for edu.entrance_cost.college_id
     *
     * @mbggenerated Sun Jan 15 18:52:28 CST 2012
     */
    public void setCollege_id(Integer college_id) {
        this.college_id = college_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edu.entrance_cost.batch_id
     *
     * @return the value of edu.entrance_cost.batch_id
     *
     * @mbggenerated Sun Jan 15 18:52:28 CST 2012
     */
    public Integer getBatch_id() {
        return batch_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edu.entrance_cost.batch_id
     *
     * @param batch_id the value for edu.entrance_cost.batch_id
     *
     * @mbggenerated Sun Jan 15 18:52:28 CST 2012
     */
    public void setBatch_id(Integer batch_id) {
        this.batch_id = batch_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edu.entrance_cost.subject_id
     *
     * @return the value of edu.entrance_cost.subject_id
     *
     * @mbggenerated Sun Jan 15 18:52:28 CST 2012
     */
    public Integer getSubject_id() {
        return subject_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edu.entrance_cost.subject_id
     *
     * @param subject_id the value for edu.entrance_cost.subject_id
     *
     * @mbggenerated Sun Jan 15 18:52:28 CST 2012
     */
    public void setSubject_id(Integer subject_id) {
        this.subject_id = subject_id;
    }
}