package com.brightedu.model.edu;

import java.io.Serializable;

public class EntranceCostKey  implements Serializable{

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column edu.entrance_cost.college_id
	 * @mbggenerated  Thu Feb 09 18:41:46 CST 2012
	 */
	private Integer college_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column edu.entrance_cost.batch_id
	 * @mbggenerated  Thu Feb 09 18:41:46 CST 2012
	 */
	private Integer batch_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column edu.entrance_cost.agent_id
	 * @mbggenerated  Thu Feb 09 18:41:46 CST 2012
	 */
	private Integer agent_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column edu.entrance_cost.subject_id
	 * @mbggenerated  Thu Feb 09 18:41:46 CST 2012
	 */
	private Integer subject_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column edu.entrance_cost.fee_id
	 * @mbggenerated  Thu Feb 09 18:41:46 CST 2012
	 */
	private Integer fee_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table edu.entrance_cost
	 * @mbggenerated  Thu Feb 09 18:41:46 CST 2012
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column edu.entrance_cost.college_id
	 * @return  the value of edu.entrance_cost.college_id
	 * @mbggenerated  Thu Feb 09 18:41:46 CST 2012
	 */
	public Integer getCollege_id() {
		return college_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column edu.entrance_cost.college_id
	 * @param college_id  the value for edu.entrance_cost.college_id
	 * @mbggenerated  Thu Feb 09 18:41:46 CST 2012
	 */
	public void setCollege_id(Integer college_id) {
		this.college_id = college_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column edu.entrance_cost.batch_id
	 * @return  the value of edu.entrance_cost.batch_id
	 * @mbggenerated  Thu Feb 09 18:41:46 CST 2012
	 */
	public Integer getBatch_id() {
		return batch_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column edu.entrance_cost.batch_id
	 * @param batch_id  the value for edu.entrance_cost.batch_id
	 * @mbggenerated  Thu Feb 09 18:41:46 CST 2012
	 */
	public void setBatch_id(Integer batch_id) {
		this.batch_id = batch_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column edu.entrance_cost.agent_id
	 * @return  the value of edu.entrance_cost.agent_id
	 * @mbggenerated  Thu Feb 09 18:41:46 CST 2012
	 */
	public Integer getAgent_id() {
		return agent_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column edu.entrance_cost.agent_id
	 * @param agent_id  the value for edu.entrance_cost.agent_id
	 * @mbggenerated  Thu Feb 09 18:41:46 CST 2012
	 */
	public void setAgent_id(Integer agent_id) {
		this.agent_id = agent_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column edu.entrance_cost.subject_id
	 * @return  the value of edu.entrance_cost.subject_id
	 * @mbggenerated  Thu Feb 09 18:41:46 CST 2012
	 */
	public Integer getSubject_id() {
		return subject_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column edu.entrance_cost.subject_id
	 * @param subject_id  the value for edu.entrance_cost.subject_id
	 * @mbggenerated  Thu Feb 09 18:41:46 CST 2012
	 */
	public void setSubject_id(Integer subject_id) {
		this.subject_id = subject_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column edu.entrance_cost.fee_id
	 * @return  the value of edu.entrance_cost.fee_id
	 * @mbggenerated  Thu Feb 09 18:41:46 CST 2012
	 */
	public Integer getFee_id() {
		return fee_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column edu.entrance_cost.fee_id
	 * @param fee_id  the value for edu.entrance_cost.fee_id
	 * @mbggenerated  Thu Feb 09 18:41:46 CST 2012
	 */
	public void setFee_id(Integer fee_id) {
		this.fee_id = fee_id;
	}
}