package com.brightedu.model.edu;

import java.math.BigDecimal;
import java.util.Date;

public class EntranceCost extends EntranceCostKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edu.entrance_cost.register_date
     *
     * @mbggenerated Sun Jan 15 18:52:28 CST 2012
     */
    private Date register_date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edu.entrance_cost.fee_id
     *
     * @mbggenerated Sun Jan 15 18:52:28 CST 2012
     */
    private Integer fee_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edu.entrance_cost.fee
     *
     * @mbggenerated Sun Jan 15 18:52:28 CST 2012
     */
    private BigDecimal fee;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edu.entrance_cost.register_date
     *
     * @return the value of edu.entrance_cost.register_date
     *
     * @mbggenerated Sun Jan 15 18:52:28 CST 2012
     */
    public Date getRegister_date() {
        return register_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edu.entrance_cost.register_date
     *
     * @param register_date the value for edu.entrance_cost.register_date
     *
     * @mbggenerated Sun Jan 15 18:52:28 CST 2012
     */
    public void setRegister_date(Date register_date) {
        this.register_date = register_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edu.entrance_cost.fee_id
     *
     * @return the value of edu.entrance_cost.fee_id
     *
     * @mbggenerated Sun Jan 15 18:52:28 CST 2012
     */
    public Integer getFee_id() {
        return fee_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edu.entrance_cost.fee_id
     *
     * @param fee_id the value for edu.entrance_cost.fee_id
     *
     * @mbggenerated Sun Jan 15 18:52:28 CST 2012
     */
    public void setFee_id(Integer fee_id) {
        this.fee_id = fee_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edu.entrance_cost.fee
     *
     * @return the value of edu.entrance_cost.fee
     *
     * @mbggenerated Sun Jan 15 18:52:28 CST 2012
     */
    public BigDecimal getFee() {
        return fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edu.entrance_cost.fee
     *
     * @param fee the value for edu.entrance_cost.fee
     *
     * @mbggenerated Sun Jan 15 18:52:28 CST 2012
     */
    public void setFee(BigDecimal fee) {
        this.fee = fee;
    }
}