package com.brightedu.model.edu;

import java.io.Serializable;
import java.util.Date;

public class Messages implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edu.messages.message_id
     *
     * @mbggenerated Tue Feb 28 14:45:50 CST 2012
     */
    private Long message_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edu.messages.from_user
     *
     * @mbggenerated Tue Feb 28 14:45:50 CST 2012
     */
    private Integer from_user;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edu.messages.to_user
     *
     * @mbggenerated Tue Feb 28 14:45:50 CST 2012
     */
    private Integer to_user;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edu.messages.message
     *
     * @mbggenerated Tue Feb 28 14:45:50 CST 2012
     */
    private String message;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edu.messages.is_read
     *
     * @mbggenerated Tue Feb 28 14:45:50 CST 2012
     */
    private Boolean is_read;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edu.messages.receive_tstp
     *
     * @mbggenerated Tue Feb 28 14:45:50 CST 2012
     */
    private Date receive_tstp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edu.messages.read_tstp
     *
     * @mbggenerated Tue Feb 28 14:45:50 CST 2012
     */
    private Date read_tstp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table edu.messages
     *
     * @mbggenerated Tue Feb 28 14:45:50 CST 2012
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edu.messages.message_id
     *
     * @return the value of edu.messages.message_id
     *
     * @mbggenerated Tue Feb 28 14:45:50 CST 2012
     */
    public Long getMessage_id() {
        return message_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edu.messages.message_id
     *
     * @param message_id the value for edu.messages.message_id
     *
     * @mbggenerated Tue Feb 28 14:45:50 CST 2012
     */
    public void setMessage_id(Long message_id) {
        this.message_id = message_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edu.messages.from_user
     *
     * @return the value of edu.messages.from_user
     *
     * @mbggenerated Tue Feb 28 14:45:50 CST 2012
     */
    public Integer getFrom_user() {
        return from_user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edu.messages.from_user
     *
     * @param from_user the value for edu.messages.from_user
     *
     * @mbggenerated Tue Feb 28 14:45:50 CST 2012
     */
    public void setFrom_user(Integer from_user) {
        this.from_user = from_user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edu.messages.to_user
     *
     * @return the value of edu.messages.to_user
     *
     * @mbggenerated Tue Feb 28 14:45:50 CST 2012
     */
    public Integer getTo_user() {
        return to_user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edu.messages.to_user
     *
     * @param to_user the value for edu.messages.to_user
     *
     * @mbggenerated Tue Feb 28 14:45:50 CST 2012
     */
    public void setTo_user(Integer to_user) {
        this.to_user = to_user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edu.messages.message
     *
     * @return the value of edu.messages.message
     *
     * @mbggenerated Tue Feb 28 14:45:50 CST 2012
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edu.messages.message
     *
     * @param message the value for edu.messages.message
     *
     * @mbggenerated Tue Feb 28 14:45:50 CST 2012
     */
    public void setMessage(String message) {
        this.message = message == null ? null : message.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edu.messages.is_read
     *
     * @return the value of edu.messages.is_read
     *
     * @mbggenerated Tue Feb 28 14:45:50 CST 2012
     */
    public Boolean getIs_read() {
        return is_read;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edu.messages.is_read
     *
     * @param is_read the value for edu.messages.is_read
     *
     * @mbggenerated Tue Feb 28 14:45:50 CST 2012
     */
    public void setIs_read(Boolean is_read) {
        this.is_read = is_read;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edu.messages.receive_tstp
     *
     * @return the value of edu.messages.receive_tstp
     *
     * @mbggenerated Tue Feb 28 14:45:50 CST 2012
     */
    public Date getReceive_tstp() {
        return receive_tstp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edu.messages.receive_tstp
     *
     * @param receive_tstp the value for edu.messages.receive_tstp
     *
     * @mbggenerated Tue Feb 28 14:45:50 CST 2012
     */
    public void setReceive_tstp(Date receive_tstp) {
        this.receive_tstp = receive_tstp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edu.messages.read_tstp
     *
     * @return the value of edu.messages.read_tstp
     *
     * @mbggenerated Tue Feb 28 14:45:50 CST 2012
     */
    public Date getRead_tstp() {
        return read_tstp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edu.messages.read_tstp
     *
     * @param read_tstp the value for edu.messages.read_tstp
     *
     * @mbggenerated Tue Feb 28 14:45:50 CST 2012
     */
    public void setRead_tstp(Date read_tstp) {
        this.read_tstp = read_tstp;
    }
}