package com.brightedu.model.edu;

import java.io.Serializable;

public class PictureType implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edu.pic_type.pic_type_id
     *
     * @mbggenerated Sun Feb 12 11:48:59 CST 2012
     */
    private Integer pic_type_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edu.pic_type.pic_type_name
     *
     * @mbggenerated Sun Feb 12 11:48:59 CST 2012
     */
    private String pic_type_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table edu.pic_type
     *
     * @mbggenerated Sun Feb 12 11:48:59 CST 2012
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edu.pic_type.pic_type_id
     *
     * @return the value of edu.pic_type.pic_type_id
     *
     * @mbggenerated Sun Feb 12 11:48:59 CST 2012
     */
    public Integer getPic_type_id() {
        return pic_type_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edu.pic_type.pic_type_id
     *
     * @param pic_type_id the value for edu.pic_type.pic_type_id
     *
     * @mbggenerated Sun Feb 12 11:48:59 CST 2012
     */
    public void setPic_type_id(Integer pic_type_id) {
        this.pic_type_id = pic_type_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edu.pic_type.pic_type_name
     *
     * @return the value of edu.pic_type.pic_type_name
     *
     * @mbggenerated Sun Feb 12 11:48:59 CST 2012
     */
    public String getPic_type_name() {
        return pic_type_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edu.pic_type.pic_type_name
     *
     * @param pic_type_name the value for edu.pic_type.pic_type_name
     *
     * @mbggenerated Sun Feb 12 11:48:59 CST 2012
     */
    public void setPic_type_name(String pic_type_name) {
        this.pic_type_name = pic_type_name == null ? null : pic_type_name.trim();
    }
}