package com.brightedu.model.edu;

import java.util.Date;

public class RecruitAgent {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edu.recruit_agent.agent_id
     *
     * @mbggenerated Sun Jan 15 18:52:28 CST 2012
     */
    private Integer agent_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edu.recruit_agent.agent_name
     *
     * @mbggenerated Sun Jan 15 18:52:28 CST 2012
     */
    private String agent_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edu.recruit_agent.responsible_person
     *
     * @mbggenerated Sun Jan 15 18:52:28 CST 2012
     */
    private String responsible_person;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edu.recruit_agent.contact_person
     *
     * @mbggenerated Sun Jan 15 18:52:28 CST 2012
     */
    private String contact_person;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edu.recruit_agent.contact_address
     *
     * @mbggenerated Sun Jan 15 18:52:28 CST 2012
     */
    private String contact_address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edu.recruit_agent.contact_phone
     *
     * @mbggenerated Sun Jan 15 18:52:28 CST 2012
     */
    private String contact_phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edu.recruit_agent.user_id
     *
     * @mbggenerated Sun Jan 15 18:52:28 CST 2012
     */
    private Integer user_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edu.recruit_agent.college_url
     *
     * @mbggenerated Sun Jan 15 18:52:28 CST 2012
     */
    private String college_url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edu.recruit_agent.register_date
     *
     * @mbggenerated Sun Jan 15 18:52:28 CST 2012
     */
    private Date register_date;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edu.recruit_agent.agent_id
     *
     * @return the value of edu.recruit_agent.agent_id
     *
     * @mbggenerated Sun Jan 15 18:52:28 CST 2012
     */
    public Integer getAgent_id() {
        return agent_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edu.recruit_agent.agent_id
     *
     * @param agent_id the value for edu.recruit_agent.agent_id
     *
     * @mbggenerated Sun Jan 15 18:52:28 CST 2012
     */
    public void setAgent_id(Integer agent_id) {
        this.agent_id = agent_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edu.recruit_agent.agent_name
     *
     * @return the value of edu.recruit_agent.agent_name
     *
     * @mbggenerated Sun Jan 15 18:52:28 CST 2012
     */
    public String getAgent_name() {
        return agent_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edu.recruit_agent.agent_name
     *
     * @param agent_name the value for edu.recruit_agent.agent_name
     *
     * @mbggenerated Sun Jan 15 18:52:28 CST 2012
     */
    public void setAgent_name(String agent_name) {
        this.agent_name = agent_name == null ? null : agent_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edu.recruit_agent.responsible_person
     *
     * @return the value of edu.recruit_agent.responsible_person
     *
     * @mbggenerated Sun Jan 15 18:52:28 CST 2012
     */
    public String getResponsible_person() {
        return responsible_person;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edu.recruit_agent.responsible_person
     *
     * @param responsible_person the value for edu.recruit_agent.responsible_person
     *
     * @mbggenerated Sun Jan 15 18:52:28 CST 2012
     */
    public void setResponsible_person(String responsible_person) {
        this.responsible_person = responsible_person == null ? null : responsible_person.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edu.recruit_agent.contact_person
     *
     * @return the value of edu.recruit_agent.contact_person
     *
     * @mbggenerated Sun Jan 15 18:52:28 CST 2012
     */
    public String getContact_person() {
        return contact_person;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edu.recruit_agent.contact_person
     *
     * @param contact_person the value for edu.recruit_agent.contact_person
     *
     * @mbggenerated Sun Jan 15 18:52:28 CST 2012
     */
    public void setContact_person(String contact_person) {
        this.contact_person = contact_person == null ? null : contact_person.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edu.recruit_agent.contact_address
     *
     * @return the value of edu.recruit_agent.contact_address
     *
     * @mbggenerated Sun Jan 15 18:52:28 CST 2012
     */
    public String getContact_address() {
        return contact_address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edu.recruit_agent.contact_address
     *
     * @param contact_address the value for edu.recruit_agent.contact_address
     *
     * @mbggenerated Sun Jan 15 18:52:28 CST 2012
     */
    public void setContact_address(String contact_address) {
        this.contact_address = contact_address == null ? null : contact_address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edu.recruit_agent.contact_phone
     *
     * @return the value of edu.recruit_agent.contact_phone
     *
     * @mbggenerated Sun Jan 15 18:52:28 CST 2012
     */
    public String getContact_phone() {
        return contact_phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edu.recruit_agent.contact_phone
     *
     * @param contact_phone the value for edu.recruit_agent.contact_phone
     *
     * @mbggenerated Sun Jan 15 18:52:28 CST 2012
     */
    public void setContact_phone(String contact_phone) {
        this.contact_phone = contact_phone == null ? null : contact_phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edu.recruit_agent.user_id
     *
     * @return the value of edu.recruit_agent.user_id
     *
     * @mbggenerated Sun Jan 15 18:52:28 CST 2012
     */
    public Integer getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edu.recruit_agent.user_id
     *
     * @param user_id the value for edu.recruit_agent.user_id
     *
     * @mbggenerated Sun Jan 15 18:52:28 CST 2012
     */
    public void setUser_id(Integer user_id) {
        this.user_id = user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edu.recruit_agent.college_url
     *
     * @return the value of edu.recruit_agent.college_url
     *
     * @mbggenerated Sun Jan 15 18:52:28 CST 2012
     */
    public String getCollege_url() {
        return college_url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edu.recruit_agent.college_url
     *
     * @param college_url the value for edu.recruit_agent.college_url
     *
     * @mbggenerated Sun Jan 15 18:52:28 CST 2012
     */
    public void setCollege_url(String college_url) {
        this.college_url = college_url == null ? null : college_url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edu.recruit_agent.register_date
     *
     * @return the value of edu.recruit_agent.register_date
     *
     * @mbggenerated Sun Jan 15 18:52:28 CST 2012
     */
    public Date getRegister_date() {
        return register_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edu.recruit_agent.register_date
     *
     * @param register_date the value for edu.recruit_agent.register_date
     *
     * @mbggenerated Sun Jan 15 18:52:28 CST 2012
     */
    public void setRegister_date(Date register_date) {
        this.register_date = register_date;
    }
}