package com.brightedu.model.edu;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class StudentInfoExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table edu.student_info
	 * @mbggenerated  Thu Feb 09 18:11:26 CST 2012
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table edu.student_info
	 * @mbggenerated  Thu Feb 09 18:11:26 CST 2012
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table edu.student_info
	 * @mbggenerated  Thu Feb 09 18:11:26 CST 2012
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table edu.student_info
	 * @mbggenerated  Thu Feb 09 18:11:26 CST 2012
	 */
	public StudentInfoExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table edu.student_info
	 * @mbggenerated  Thu Feb 09 18:11:26 CST 2012
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table edu.student_info
	 * @mbggenerated  Thu Feb 09 18:11:26 CST 2012
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table edu.student_info
	 * @mbggenerated  Thu Feb 09 18:11:26 CST 2012
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table edu.student_info
	 * @mbggenerated  Thu Feb 09 18:11:26 CST 2012
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table edu.student_info
	 * @mbggenerated  Thu Feb 09 18:11:26 CST 2012
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table edu.student_info
	 * @mbggenerated  Thu Feb 09 18:11:26 CST 2012
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table edu.student_info
	 * @mbggenerated  Thu Feb 09 18:11:26 CST 2012
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table edu.student_info
	 * @mbggenerated  Thu Feb 09 18:11:26 CST 2012
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table edu.student_info
	 * @mbggenerated  Thu Feb 09 18:11:26 CST 2012
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table edu.student_info
	 * @mbggenerated  Thu Feb 09 18:11:26 CST 2012
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table edu.student_info
	 * @mbggenerated  Thu Feb 09 18:11:26 CST 2012
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andStudent_idIsNull() {
			addCriterion("student_id is null");
			return (Criteria) this;
		}

		public Criteria andStudent_idIsNotNull() {
			addCriterion("student_id is not null");
			return (Criteria) this;
		}

		public Criteria andStudent_idEqualTo(Integer value) {
			addCriterion("student_id =", value, "student_id");
			return (Criteria) this;
		}

		public Criteria andStudent_idNotEqualTo(Integer value) {
			addCriterion("student_id <>", value, "student_id");
			return (Criteria) this;
		}

		public Criteria andStudent_idGreaterThan(Integer value) {
			addCriterion("student_id >", value, "student_id");
			return (Criteria) this;
		}

		public Criteria andStudent_idGreaterThanOrEqualTo(Integer value) {
			addCriterion("student_id >=", value, "student_id");
			return (Criteria) this;
		}

		public Criteria andStudent_idLessThan(Integer value) {
			addCriterion("student_id <", value, "student_id");
			return (Criteria) this;
		}

		public Criteria andStudent_idLessThanOrEqualTo(Integer value) {
			addCriterion("student_id <=", value, "student_id");
			return (Criteria) this;
		}

		public Criteria andStudent_idIn(List<Integer> values) {
			addCriterion("student_id in", values, "student_id");
			return (Criteria) this;
		}

		public Criteria andStudent_idNotIn(List<Integer> values) {
			addCriterion("student_id not in", values, "student_id");
			return (Criteria) this;
		}

		public Criteria andStudent_idBetween(Integer value1, Integer value2) {
			addCriterion("student_id between", value1, value2, "student_id");
			return (Criteria) this;
		}

		public Criteria andStudent_idNotBetween(Integer value1, Integer value2) {
			addCriterion("student_id not between", value1, value2, "student_id");
			return (Criteria) this;
		}

		public Criteria andStudent_nameIsNull() {
			addCriterion("student_name is null");
			return (Criteria) this;
		}

		public Criteria andStudent_nameIsNotNull() {
			addCriterion("student_name is not null");
			return (Criteria) this;
		}

		public Criteria andStudent_nameEqualTo(String value) {
			addCriterion("student_name =", value, "student_name");
			return (Criteria) this;
		}

		public Criteria andStudent_nameNotEqualTo(String value) {
			addCriterion("student_name <>", value, "student_name");
			return (Criteria) this;
		}

		public Criteria andStudent_nameGreaterThan(String value) {
			addCriterion("student_name >", value, "student_name");
			return (Criteria) this;
		}

		public Criteria andStudent_nameGreaterThanOrEqualTo(String value) {
			addCriterion("student_name >=", value, "student_name");
			return (Criteria) this;
		}

		public Criteria andStudent_nameLessThan(String value) {
			addCriterion("student_name <", value, "student_name");
			return (Criteria) this;
		}

		public Criteria andStudent_nameLessThanOrEqualTo(String value) {
			addCriterion("student_name <=", value, "student_name");
			return (Criteria) this;
		}

		public Criteria andStudent_nameLike(String value) {
			addCriterion("student_name like", value, "student_name");
			return (Criteria) this;
		}

		public Criteria andStudent_nameNotLike(String value) {
			addCriterion("student_name not like", value, "student_name");
			return (Criteria) this;
		}

		public Criteria andStudent_nameIn(List<String> values) {
			addCriterion("student_name in", values, "student_name");
			return (Criteria) this;
		}

		public Criteria andStudent_nameNotIn(List<String> values) {
			addCriterion("student_name not in", values, "student_name");
			return (Criteria) this;
		}

		public Criteria andStudent_nameBetween(String value1, String value2) {
			addCriterion("student_name between", value1, value2, "student_name");
			return (Criteria) this;
		}

		public Criteria andStudent_nameNotBetween(String value1, String value2) {
			addCriterion("student_name not between", value1, value2,
					"student_name");
			return (Criteria) this;
		}

		public Criteria andIdentity_cardIsNull() {
			addCriterion("identity_card is null");
			return (Criteria) this;
		}

		public Criteria andIdentity_cardIsNotNull() {
			addCriterion("identity_card is not null");
			return (Criteria) this;
		}

		public Criteria andIdentity_cardEqualTo(String value) {
			addCriterion("identity_card =", value, "identity_card");
			return (Criteria) this;
		}

		public Criteria andIdentity_cardNotEqualTo(String value) {
			addCriterion("identity_card <>", value, "identity_card");
			return (Criteria) this;
		}

		public Criteria andIdentity_cardGreaterThan(String value) {
			addCriterion("identity_card >", value, "identity_card");
			return (Criteria) this;
		}

		public Criteria andIdentity_cardGreaterThanOrEqualTo(String value) {
			addCriterion("identity_card >=", value, "identity_card");
			return (Criteria) this;
		}

		public Criteria andIdentity_cardLessThan(String value) {
			addCriterion("identity_card <", value, "identity_card");
			return (Criteria) this;
		}

		public Criteria andIdentity_cardLessThanOrEqualTo(String value) {
			addCriterion("identity_card <=", value, "identity_card");
			return (Criteria) this;
		}

		public Criteria andIdentity_cardLike(String value) {
			addCriterion("identity_card like", value, "identity_card");
			return (Criteria) this;
		}

		public Criteria andIdentity_cardNotLike(String value) {
			addCriterion("identity_card not like", value, "identity_card");
			return (Criteria) this;
		}

		public Criteria andIdentity_cardIn(List<String> values) {
			addCriterion("identity_card in", values, "identity_card");
			return (Criteria) this;
		}

		public Criteria andIdentity_cardNotIn(List<String> values) {
			addCriterion("identity_card not in", values, "identity_card");
			return (Criteria) this;
		}

		public Criteria andIdentity_cardBetween(String value1, String value2) {
			addCriterion("identity_card between", value1, value2,
					"identity_card");
			return (Criteria) this;
		}

		public Criteria andIdentity_cardNotBetween(String value1, String value2) {
			addCriterion("identity_card not between", value1, value2,
					"identity_card");
			return (Criteria) this;
		}

		public Criteria andExam_numIsNull() {
			addCriterion("exam_num is null");
			return (Criteria) this;
		}

		public Criteria andExam_numIsNotNull() {
			addCriterion("exam_num is not null");
			return (Criteria) this;
		}

		public Criteria andExam_numEqualTo(String value) {
			addCriterion("exam_num =", value, "exam_num");
			return (Criteria) this;
		}

		public Criteria andExam_numNotEqualTo(String value) {
			addCriterion("exam_num <>", value, "exam_num");
			return (Criteria) this;
		}

		public Criteria andExam_numGreaterThan(String value) {
			addCriterion("exam_num >", value, "exam_num");
			return (Criteria) this;
		}

		public Criteria andExam_numGreaterThanOrEqualTo(String value) {
			addCriterion("exam_num >=", value, "exam_num");
			return (Criteria) this;
		}

		public Criteria andExam_numLessThan(String value) {
			addCriterion("exam_num <", value, "exam_num");
			return (Criteria) this;
		}

		public Criteria andExam_numLessThanOrEqualTo(String value) {
			addCriterion("exam_num <=", value, "exam_num");
			return (Criteria) this;
		}

		public Criteria andExam_numLike(String value) {
			addCriterion("exam_num like", value, "exam_num");
			return (Criteria) this;
		}

		public Criteria andExam_numNotLike(String value) {
			addCriterion("exam_num not like", value, "exam_num");
			return (Criteria) this;
		}

		public Criteria andExam_numIn(List<String> values) {
			addCriterion("exam_num in", values, "exam_num");
			return (Criteria) this;
		}

		public Criteria andExam_numNotIn(List<String> values) {
			addCriterion("exam_num not in", values, "exam_num");
			return (Criteria) this;
		}

		public Criteria andExam_numBetween(String value1, String value2) {
			addCriterion("exam_num between", value1, value2, "exam_num");
			return (Criteria) this;
		}

		public Criteria andExam_numNotBetween(String value1, String value2) {
			addCriterion("exam_num not between", value1, value2, "exam_num");
			return (Criteria) this;
		}

		public Criteria andStudent_addressIsNull() {
			addCriterion("student_address is null");
			return (Criteria) this;
		}

		public Criteria andStudent_addressIsNotNull() {
			addCriterion("student_address is not null");
			return (Criteria) this;
		}

		public Criteria andStudent_addressEqualTo(String value) {
			addCriterion("student_address =", value, "student_address");
			return (Criteria) this;
		}

		public Criteria andStudent_addressNotEqualTo(String value) {
			addCriterion("student_address <>", value, "student_address");
			return (Criteria) this;
		}

		public Criteria andStudent_addressGreaterThan(String value) {
			addCriterion("student_address >", value, "student_address");
			return (Criteria) this;
		}

		public Criteria andStudent_addressGreaterThanOrEqualTo(String value) {
			addCriterion("student_address >=", value, "student_address");
			return (Criteria) this;
		}

		public Criteria andStudent_addressLessThan(String value) {
			addCriterion("student_address <", value, "student_address");
			return (Criteria) this;
		}

		public Criteria andStudent_addressLessThanOrEqualTo(String value) {
			addCriterion("student_address <=", value, "student_address");
			return (Criteria) this;
		}

		public Criteria andStudent_addressLike(String value) {
			addCriterion("student_address like", value, "student_address");
			return (Criteria) this;
		}

		public Criteria andStudent_addressNotLike(String value) {
			addCriterion("student_address not like", value, "student_address");
			return (Criteria) this;
		}

		public Criteria andStudent_addressIn(List<String> values) {
			addCriterion("student_address in", values, "student_address");
			return (Criteria) this;
		}

		public Criteria andStudent_addressNotIn(List<String> values) {
			addCriterion("student_address not in", values, "student_address");
			return (Criteria) this;
		}

		public Criteria andStudent_addressBetween(String value1, String value2) {
			addCriterion("student_address between", value1, value2,
					"student_address");
			return (Criteria) this;
		}

		public Criteria andStudent_addressNotBetween(String value1,
				String value2) {
			addCriterion("student_address not between", value1, value2,
					"student_address");
			return (Criteria) this;
		}

		public Criteria andStudent_phoneIsNull() {
			addCriterion("student_phone is null");
			return (Criteria) this;
		}

		public Criteria andStudent_phoneIsNotNull() {
			addCriterion("student_phone is not null");
			return (Criteria) this;
		}

		public Criteria andStudent_phoneEqualTo(String value) {
			addCriterion("student_phone =", value, "student_phone");
			return (Criteria) this;
		}

		public Criteria andStudent_phoneNotEqualTo(String value) {
			addCriterion("student_phone <>", value, "student_phone");
			return (Criteria) this;
		}

		public Criteria andStudent_phoneGreaterThan(String value) {
			addCriterion("student_phone >", value, "student_phone");
			return (Criteria) this;
		}

		public Criteria andStudent_phoneGreaterThanOrEqualTo(String value) {
			addCriterion("student_phone >=", value, "student_phone");
			return (Criteria) this;
		}

		public Criteria andStudent_phoneLessThan(String value) {
			addCriterion("student_phone <", value, "student_phone");
			return (Criteria) this;
		}

		public Criteria andStudent_phoneLessThanOrEqualTo(String value) {
			addCriterion("student_phone <=", value, "student_phone");
			return (Criteria) this;
		}

		public Criteria andStudent_phoneLike(String value) {
			addCriterion("student_phone like", value, "student_phone");
			return (Criteria) this;
		}

		public Criteria andStudent_phoneNotLike(String value) {
			addCriterion("student_phone not like", value, "student_phone");
			return (Criteria) this;
		}

		public Criteria andStudent_phoneIn(List<String> values) {
			addCriterion("student_phone in", values, "student_phone");
			return (Criteria) this;
		}

		public Criteria andStudent_phoneNotIn(List<String> values) {
			addCriterion("student_phone not in", values, "student_phone");
			return (Criteria) this;
		}

		public Criteria andStudent_phoneBetween(String value1, String value2) {
			addCriterion("student_phone between", value1, value2,
					"student_phone");
			return (Criteria) this;
		}

		public Criteria andStudent_phoneNotBetween(String value1, String value2) {
			addCriterion("student_phone not between", value1, value2,
					"student_phone");
			return (Criteria) this;
		}

		public Criteria andStudent_linkmanIsNull() {
			addCriterion("student_linkman is null");
			return (Criteria) this;
		}

		public Criteria andStudent_linkmanIsNotNull() {
			addCriterion("student_linkman is not null");
			return (Criteria) this;
		}

		public Criteria andStudent_linkmanEqualTo(String value) {
			addCriterion("student_linkman =", value, "student_linkman");
			return (Criteria) this;
		}

		public Criteria andStudent_linkmanNotEqualTo(String value) {
			addCriterion("student_linkman <>", value, "student_linkman");
			return (Criteria) this;
		}

		public Criteria andStudent_linkmanGreaterThan(String value) {
			addCriterion("student_linkman >", value, "student_linkman");
			return (Criteria) this;
		}

		public Criteria andStudent_linkmanGreaterThanOrEqualTo(String value) {
			addCriterion("student_linkman >=", value, "student_linkman");
			return (Criteria) this;
		}

		public Criteria andStudent_linkmanLessThan(String value) {
			addCriterion("student_linkman <", value, "student_linkman");
			return (Criteria) this;
		}

		public Criteria andStudent_linkmanLessThanOrEqualTo(String value) {
			addCriterion("student_linkman <=", value, "student_linkman");
			return (Criteria) this;
		}

		public Criteria andStudent_linkmanLike(String value) {
			addCriterion("student_linkman like", value, "student_linkman");
			return (Criteria) this;
		}

		public Criteria andStudent_linkmanNotLike(String value) {
			addCriterion("student_linkman not like", value, "student_linkman");
			return (Criteria) this;
		}

		public Criteria andStudent_linkmanIn(List<String> values) {
			addCriterion("student_linkman in", values, "student_linkman");
			return (Criteria) this;
		}

		public Criteria andStudent_linkmanNotIn(List<String> values) {
			addCriterion("student_linkman not in", values, "student_linkman");
			return (Criteria) this;
		}

		public Criteria andStudent_linkmanBetween(String value1, String value2) {
			addCriterion("student_linkman between", value1, value2,
					"student_linkman");
			return (Criteria) this;
		}

		public Criteria andStudent_linkmanNotBetween(String value1,
				String value2) {
			addCriterion("student_linkman not between", value1, value2,
					"student_linkman");
			return (Criteria) this;
		}

		public Criteria andLinkman_phoneIsNull() {
			addCriterion("linkman_phone is null");
			return (Criteria) this;
		}

		public Criteria andLinkman_phoneIsNotNull() {
			addCriterion("linkman_phone is not null");
			return (Criteria) this;
		}

		public Criteria andLinkman_phoneEqualTo(String value) {
			addCriterion("linkman_phone =", value, "linkman_phone");
			return (Criteria) this;
		}

		public Criteria andLinkman_phoneNotEqualTo(String value) {
			addCriterion("linkman_phone <>", value, "linkman_phone");
			return (Criteria) this;
		}

		public Criteria andLinkman_phoneGreaterThan(String value) {
			addCriterion("linkman_phone >", value, "linkman_phone");
			return (Criteria) this;
		}

		public Criteria andLinkman_phoneGreaterThanOrEqualTo(String value) {
			addCriterion("linkman_phone >=", value, "linkman_phone");
			return (Criteria) this;
		}

		public Criteria andLinkman_phoneLessThan(String value) {
			addCriterion("linkman_phone <", value, "linkman_phone");
			return (Criteria) this;
		}

		public Criteria andLinkman_phoneLessThanOrEqualTo(String value) {
			addCriterion("linkman_phone <=", value, "linkman_phone");
			return (Criteria) this;
		}

		public Criteria andLinkman_phoneLike(String value) {
			addCriterion("linkman_phone like", value, "linkman_phone");
			return (Criteria) this;
		}

		public Criteria andLinkman_phoneNotLike(String value) {
			addCriterion("linkman_phone not like", value, "linkman_phone");
			return (Criteria) this;
		}

		public Criteria andLinkman_phoneIn(List<String> values) {
			addCriterion("linkman_phone in", values, "linkman_phone");
			return (Criteria) this;
		}

		public Criteria andLinkman_phoneNotIn(List<String> values) {
			addCriterion("linkman_phone not in", values, "linkman_phone");
			return (Criteria) this;
		}

		public Criteria andLinkman_phoneBetween(String value1, String value2) {
			addCriterion("linkman_phone between", value1, value2,
					"linkman_phone");
			return (Criteria) this;
		}

		public Criteria andLinkman_phoneNotBetween(String value1, String value2) {
			addCriterion("linkman_phone not between", value1, value2,
					"linkman_phone");
			return (Criteria) this;
		}

		public Criteria andStudent_college_idIsNull() {
			addCriterion("student_college_id is null");
			return (Criteria) this;
		}

		public Criteria andStudent_college_idIsNotNull() {
			addCriterion("student_college_id is not null");
			return (Criteria) this;
		}

		public Criteria andStudent_college_idEqualTo(String value) {
			addCriterion("student_college_id =", value, "student_college_id");
			return (Criteria) this;
		}

		public Criteria andStudent_college_idNotEqualTo(String value) {
			addCriterion("student_college_id <>", value, "student_college_id");
			return (Criteria) this;
		}

		public Criteria andStudent_college_idGreaterThan(String value) {
			addCriterion("student_college_id >", value, "student_college_id");
			return (Criteria) this;
		}

		public Criteria andStudent_college_idGreaterThanOrEqualTo(String value) {
			addCriterion("student_college_id >=", value, "student_college_id");
			return (Criteria) this;
		}

		public Criteria andStudent_college_idLessThan(String value) {
			addCriterion("student_college_id <", value, "student_college_id");
			return (Criteria) this;
		}

		public Criteria andStudent_college_idLessThanOrEqualTo(String value) {
			addCriterion("student_college_id <=", value, "student_college_id");
			return (Criteria) this;
		}

		public Criteria andStudent_college_idLike(String value) {
			addCriterion("student_college_id like", value, "student_college_id");
			return (Criteria) this;
		}

		public Criteria andStudent_college_idNotLike(String value) {
			addCriterion("student_college_id not like", value,
					"student_college_id");
			return (Criteria) this;
		}

		public Criteria andStudent_college_idIn(List<String> values) {
			addCriterion("student_college_id in", values, "student_college_id");
			return (Criteria) this;
		}

		public Criteria andStudent_college_idNotIn(List<String> values) {
			addCriterion("student_college_id not in", values,
					"student_college_id");
			return (Criteria) this;
		}

		public Criteria andStudent_college_idBetween(String value1,
				String value2) {
			addCriterion("student_college_id between", value1, value2,
					"student_college_id");
			return (Criteria) this;
		}

		public Criteria andStudent_college_idNotBetween(String value1,
				String value2) {
			addCriterion("student_college_id not between", value1, value2,
					"student_college_id");
			return (Criteria) this;
		}

		public Criteria andCollege_ownerIsNull() {
			addCriterion("college_owner is null");
			return (Criteria) this;
		}

		public Criteria andCollege_ownerIsNotNull() {
			addCriterion("college_owner is not null");
			return (Criteria) this;
		}

		public Criteria andCollege_ownerEqualTo(Integer value) {
			addCriterion("college_owner =", value, "college_owner");
			return (Criteria) this;
		}

		public Criteria andCollege_ownerNotEqualTo(Integer value) {
			addCriterion("college_owner <>", value, "college_owner");
			return (Criteria) this;
		}

		public Criteria andCollege_ownerGreaterThan(Integer value) {
			addCriterion("college_owner >", value, "college_owner");
			return (Criteria) this;
		}

		public Criteria andCollege_ownerGreaterThanOrEqualTo(Integer value) {
			addCriterion("college_owner >=", value, "college_owner");
			return (Criteria) this;
		}

		public Criteria andCollege_ownerLessThan(Integer value) {
			addCriterion("college_owner <", value, "college_owner");
			return (Criteria) this;
		}

		public Criteria andCollege_ownerLessThanOrEqualTo(Integer value) {
			addCriterion("college_owner <=", value, "college_owner");
			return (Criteria) this;
		}

		public Criteria andCollege_ownerIn(List<Integer> values) {
			addCriterion("college_owner in", values, "college_owner");
			return (Criteria) this;
		}

		public Criteria andCollege_ownerNotIn(List<Integer> values) {
			addCriterion("college_owner not in", values, "college_owner");
			return (Criteria) this;
		}

		public Criteria andCollege_ownerBetween(Integer value1, Integer value2) {
			addCriterion("college_owner between", value1, value2,
					"college_owner");
			return (Criteria) this;
		}

		public Criteria andCollege_ownerNotBetween(Integer value1,
				Integer value2) {
			addCriterion("college_owner not between", value1, value2,
					"college_owner");
			return (Criteria) this;
		}

		public Criteria andBatch_ownerIsNull() {
			addCriterion("batch_owner is null");
			return (Criteria) this;
		}

		public Criteria andBatch_ownerIsNotNull() {
			addCriterion("batch_owner is not null");
			return (Criteria) this;
		}

		public Criteria andBatch_ownerEqualTo(Integer value) {
			addCriterion("batch_owner =", value, "batch_owner");
			return (Criteria) this;
		}

		public Criteria andBatch_ownerNotEqualTo(Integer value) {
			addCriterion("batch_owner <>", value, "batch_owner");
			return (Criteria) this;
		}

		public Criteria andBatch_ownerGreaterThan(Integer value) {
			addCriterion("batch_owner >", value, "batch_owner");
			return (Criteria) this;
		}

		public Criteria andBatch_ownerGreaterThanOrEqualTo(Integer value) {
			addCriterion("batch_owner >=", value, "batch_owner");
			return (Criteria) this;
		}

		public Criteria andBatch_ownerLessThan(Integer value) {
			addCriterion("batch_owner <", value, "batch_owner");
			return (Criteria) this;
		}

		public Criteria andBatch_ownerLessThanOrEqualTo(Integer value) {
			addCriterion("batch_owner <=", value, "batch_owner");
			return (Criteria) this;
		}

		public Criteria andBatch_ownerIn(List<Integer> values) {
			addCriterion("batch_owner in", values, "batch_owner");
			return (Criteria) this;
		}

		public Criteria andBatch_ownerNotIn(List<Integer> values) {
			addCriterion("batch_owner not in", values, "batch_owner");
			return (Criteria) this;
		}

		public Criteria andBatch_ownerBetween(Integer value1, Integer value2) {
			addCriterion("batch_owner between", value1, value2, "batch_owner");
			return (Criteria) this;
		}

		public Criteria andBatch_ownerNotBetween(Integer value1, Integer value2) {
			addCriterion("batch_owner not between", value1, value2,
					"batch_owner");
			return (Criteria) this;
		}

		public Criteria andClassified_ownerIsNull() {
			addCriterion("classified_owner is null");
			return (Criteria) this;
		}

		public Criteria andClassified_ownerIsNotNull() {
			addCriterion("classified_owner is not null");
			return (Criteria) this;
		}

		public Criteria andClassified_ownerEqualTo(Integer value) {
			addCriterion("classified_owner =", value, "classified_owner");
			return (Criteria) this;
		}

		public Criteria andClassified_ownerNotEqualTo(Integer value) {
			addCriterion("classified_owner <>", value, "classified_owner");
			return (Criteria) this;
		}

		public Criteria andClassified_ownerGreaterThan(Integer value) {
			addCriterion("classified_owner >", value, "classified_owner");
			return (Criteria) this;
		}

		public Criteria andClassified_ownerGreaterThanOrEqualTo(Integer value) {
			addCriterion("classified_owner >=", value, "classified_owner");
			return (Criteria) this;
		}

		public Criteria andClassified_ownerLessThan(Integer value) {
			addCriterion("classified_owner <", value, "classified_owner");
			return (Criteria) this;
		}

		public Criteria andClassified_ownerLessThanOrEqualTo(Integer value) {
			addCriterion("classified_owner <=", value, "classified_owner");
			return (Criteria) this;
		}

		public Criteria andClassified_ownerIn(List<Integer> values) {
			addCriterion("classified_owner in", values, "classified_owner");
			return (Criteria) this;
		}

		public Criteria andClassified_ownerNotIn(List<Integer> values) {
			addCriterion("classified_owner not in", values, "classified_owner");
			return (Criteria) this;
		}

		public Criteria andClassified_ownerBetween(Integer value1,
				Integer value2) {
			addCriterion("classified_owner between", value1, value2,
					"classified_owner");
			return (Criteria) this;
		}

		public Criteria andClassified_ownerNotBetween(Integer value1,
				Integer value2) {
			addCriterion("classified_owner not between", value1, value2,
					"classified_owner");
			return (Criteria) this;
		}

		public Criteria andSubject_ownerIsNull() {
			addCriterion("subject_owner is null");
			return (Criteria) this;
		}

		public Criteria andSubject_ownerIsNotNull() {
			addCriterion("subject_owner is not null");
			return (Criteria) this;
		}

		public Criteria andSubject_ownerEqualTo(Integer value) {
			addCriterion("subject_owner =", value, "subject_owner");
			return (Criteria) this;
		}

		public Criteria andSubject_ownerNotEqualTo(Integer value) {
			addCriterion("subject_owner <>", value, "subject_owner");
			return (Criteria) this;
		}

		public Criteria andSubject_ownerGreaterThan(Integer value) {
			addCriterion("subject_owner >", value, "subject_owner");
			return (Criteria) this;
		}

		public Criteria andSubject_ownerGreaterThanOrEqualTo(Integer value) {
			addCriterion("subject_owner >=", value, "subject_owner");
			return (Criteria) this;
		}

		public Criteria andSubject_ownerLessThan(Integer value) {
			addCriterion("subject_owner <", value, "subject_owner");
			return (Criteria) this;
		}

		public Criteria andSubject_ownerLessThanOrEqualTo(Integer value) {
			addCriterion("subject_owner <=", value, "subject_owner");
			return (Criteria) this;
		}

		public Criteria andSubject_ownerIn(List<Integer> values) {
			addCriterion("subject_owner in", values, "subject_owner");
			return (Criteria) this;
		}

		public Criteria andSubject_ownerNotIn(List<Integer> values) {
			addCriterion("subject_owner not in", values, "subject_owner");
			return (Criteria) this;
		}

		public Criteria andSubject_ownerBetween(Integer value1, Integer value2) {
			addCriterion("subject_owner between", value1, value2,
					"subject_owner");
			return (Criteria) this;
		}

		public Criteria andSubject_ownerNotBetween(Integer value1,
				Integer value2) {
			addCriterion("subject_owner not between", value1, value2,
					"subject_owner");
			return (Criteria) this;
		}

		public Criteria andAgent_ownerIsNull() {
			addCriterion("agent_owner is null");
			return (Criteria) this;
		}

		public Criteria andAgent_ownerIsNotNull() {
			addCriterion("agent_owner is not null");
			return (Criteria) this;
		}

		public Criteria andAgent_ownerEqualTo(Integer value) {
			addCriterion("agent_owner =", value, "agent_owner");
			return (Criteria) this;
		}

		public Criteria andAgent_ownerNotEqualTo(Integer value) {
			addCriterion("agent_owner <>", value, "agent_owner");
			return (Criteria) this;
		}

		public Criteria andAgent_ownerGreaterThan(Integer value) {
			addCriterion("agent_owner >", value, "agent_owner");
			return (Criteria) this;
		}

		public Criteria andAgent_ownerGreaterThanOrEqualTo(Integer value) {
			addCriterion("agent_owner >=", value, "agent_owner");
			return (Criteria) this;
		}

		public Criteria andAgent_ownerLessThan(Integer value) {
			addCriterion("agent_owner <", value, "agent_owner");
			return (Criteria) this;
		}

		public Criteria andAgent_ownerLessThanOrEqualTo(Integer value) {
			addCriterion("agent_owner <=", value, "agent_owner");
			return (Criteria) this;
		}

		public Criteria andAgent_ownerIn(List<Integer> values) {
			addCriterion("agent_owner in", values, "agent_owner");
			return (Criteria) this;
		}

		public Criteria andAgent_ownerNotIn(List<Integer> values) {
			addCriterion("agent_owner not in", values, "agent_owner");
			return (Criteria) this;
		}

		public Criteria andAgent_ownerBetween(Integer value1, Integer value2) {
			addCriterion("agent_owner between", value1, value2, "agent_owner");
			return (Criteria) this;
		}

		public Criteria andAgent_ownerNotBetween(Integer value1, Integer value2) {
			addCriterion("agent_owner not between", value1, value2,
					"agent_owner");
			return (Criteria) this;
		}

		public Criteria andFund_agentIsNull() {
			addCriterion("fund_agent is null");
			return (Criteria) this;
		}

		public Criteria andFund_agentIsNotNull() {
			addCriterion("fund_agent is not null");
			return (Criteria) this;
		}

		public Criteria andFund_agentEqualTo(Integer value) {
			addCriterion("fund_agent =", value, "fund_agent");
			return (Criteria) this;
		}

		public Criteria andFund_agentNotEqualTo(Integer value) {
			addCriterion("fund_agent <>", value, "fund_agent");
			return (Criteria) this;
		}

		public Criteria andFund_agentGreaterThan(Integer value) {
			addCriterion("fund_agent >", value, "fund_agent");
			return (Criteria) this;
		}

		public Criteria andFund_agentGreaterThanOrEqualTo(Integer value) {
			addCriterion("fund_agent >=", value, "fund_agent");
			return (Criteria) this;
		}

		public Criteria andFund_agentLessThan(Integer value) {
			addCriterion("fund_agent <", value, "fund_agent");
			return (Criteria) this;
		}

		public Criteria andFund_agentLessThanOrEqualTo(Integer value) {
			addCriterion("fund_agent <=", value, "fund_agent");
			return (Criteria) this;
		}

		public Criteria andFund_agentIn(List<Integer> values) {
			addCriterion("fund_agent in", values, "fund_agent");
			return (Criteria) this;
		}

		public Criteria andFund_agentNotIn(List<Integer> values) {
			addCriterion("fund_agent not in", values, "fund_agent");
			return (Criteria) this;
		}

		public Criteria andFund_agentBetween(Integer value1, Integer value2) {
			addCriterion("fund_agent between", value1, value2, "fund_agent");
			return (Criteria) this;
		}

		public Criteria andFund_agentNotBetween(Integer value1, Integer value2) {
			addCriterion("fund_agent not between", value1, value2, "fund_agent");
			return (Criteria) this;
		}

		public Criteria andManaged_agentIsNull() {
			addCriterion("managed_agent is null");
			return (Criteria) this;
		}

		public Criteria andManaged_agentIsNotNull() {
			addCriterion("managed_agent is not null");
			return (Criteria) this;
		}

		public Criteria andManaged_agentEqualTo(Integer value) {
			addCriterion("managed_agent =", value, "managed_agent");
			return (Criteria) this;
		}

		public Criteria andManaged_agentNotEqualTo(Integer value) {
			addCriterion("managed_agent <>", value, "managed_agent");
			return (Criteria) this;
		}

		public Criteria andManaged_agentGreaterThan(Integer value) {
			addCriterion("managed_agent >", value, "managed_agent");
			return (Criteria) this;
		}

		public Criteria andManaged_agentGreaterThanOrEqualTo(Integer value) {
			addCriterion("managed_agent >=", value, "managed_agent");
			return (Criteria) this;
		}

		public Criteria andManaged_agentLessThan(Integer value) {
			addCriterion("managed_agent <", value, "managed_agent");
			return (Criteria) this;
		}

		public Criteria andManaged_agentLessThanOrEqualTo(Integer value) {
			addCriterion("managed_agent <=", value, "managed_agent");
			return (Criteria) this;
		}

		public Criteria andManaged_agentIn(List<Integer> values) {
			addCriterion("managed_agent in", values, "managed_agent");
			return (Criteria) this;
		}

		public Criteria andManaged_agentNotIn(List<Integer> values) {
			addCriterion("managed_agent not in", values, "managed_agent");
			return (Criteria) this;
		}

		public Criteria andManaged_agentBetween(Integer value1, Integer value2) {
			addCriterion("managed_agent between", value1, value2,
					"managed_agent");
			return (Criteria) this;
		}

		public Criteria andManaged_agentNotBetween(Integer value1,
				Integer value2) {
			addCriterion("managed_agent not between", value1, value2,
					"managed_agent");
			return (Criteria) this;
		}

		public Criteria andStu_status_idIsNull() {
			addCriterion("stu_status_id is null");
			return (Criteria) this;
		}

		public Criteria andStu_status_idIsNotNull() {
			addCriterion("stu_status_id is not null");
			return (Criteria) this;
		}

		public Criteria andStu_status_idEqualTo(Integer value) {
			addCriterion("stu_status_id =", value, "stu_status_id");
			return (Criteria) this;
		}

		public Criteria andStu_status_idNotEqualTo(Integer value) {
			addCriterion("stu_status_id <>", value, "stu_status_id");
			return (Criteria) this;
		}

		public Criteria andStu_status_idGreaterThan(Integer value) {
			addCriterion("stu_status_id >", value, "stu_status_id");
			return (Criteria) this;
		}

		public Criteria andStu_status_idGreaterThanOrEqualTo(Integer value) {
			addCriterion("stu_status_id >=", value, "stu_status_id");
			return (Criteria) this;
		}

		public Criteria andStu_status_idLessThan(Integer value) {
			addCriterion("stu_status_id <", value, "stu_status_id");
			return (Criteria) this;
		}

		public Criteria andStu_status_idLessThanOrEqualTo(Integer value) {
			addCriterion("stu_status_id <=", value, "stu_status_id");
			return (Criteria) this;
		}

		public Criteria andStu_status_idIn(List<Integer> values) {
			addCriterion("stu_status_id in", values, "stu_status_id");
			return (Criteria) this;
		}

		public Criteria andStu_status_idNotIn(List<Integer> values) {
			addCriterion("stu_status_id not in", values, "stu_status_id");
			return (Criteria) this;
		}

		public Criteria andStu_status_idBetween(Integer value1, Integer value2) {
			addCriterion("stu_status_id between", value1, value2,
					"stu_status_id");
			return (Criteria) this;
		}

		public Criteria andStu_status_idNotBetween(Integer value1,
				Integer value2) {
			addCriterion("stu_status_id not between", value1, value2,
					"stu_status_id");
			return (Criteria) this;
		}

		public Criteria andRegister_dateIsNull() {
			addCriterion("register_date is null");
			return (Criteria) this;
		}

		public Criteria andRegister_dateIsNotNull() {
			addCriterion("register_date is not null");
			return (Criteria) this;
		}

		public Criteria andRegister_dateEqualTo(Date value) {
			addCriterion("register_date =", value, "register_date");
			return (Criteria) this;
		}

		public Criteria andRegister_dateNotEqualTo(Date value) {
			addCriterion("register_date <>", value, "register_date");
			return (Criteria) this;
		}

		public Criteria andRegister_dateGreaterThan(Date value) {
			addCriterion("register_date >", value, "register_date");
			return (Criteria) this;
		}

		public Criteria andRegister_dateGreaterThanOrEqualTo(Date value) {
			addCriterion("register_date >=", value, "register_date");
			return (Criteria) this;
		}

		public Criteria andRegister_dateLessThan(Date value) {
			addCriterion("register_date <", value, "register_date");
			return (Criteria) this;
		}

		public Criteria andRegister_dateLessThanOrEqualTo(Date value) {
			addCriterion("register_date <=", value, "register_date");
			return (Criteria) this;
		}

		public Criteria andRegister_dateIn(List<Date> values) {
			addCriterion("register_date in", values, "register_date");
			return (Criteria) this;
		}

		public Criteria andRegister_dateNotIn(List<Date> values) {
			addCriterion("register_date not in", values, "register_date");
			return (Criteria) this;
		}

		public Criteria andRegister_dateBetween(Date value1, Date value2) {
			addCriterion("register_date between", value1, value2,
					"register_date");
			return (Criteria) this;
		}

		public Criteria andRegister_dateNotBetween(Date value1, Date value2) {
			addCriterion("register_date not between", value1, value2,
					"register_date");
			return (Criteria) this;
		}

		public Criteria andUpdate_dateIsNull() {
			addCriterion("update_date is null");
			return (Criteria) this;
		}

		public Criteria andUpdate_dateIsNotNull() {
			addCriterion("update_date is not null");
			return (Criteria) this;
		}

		public Criteria andUpdate_dateEqualTo(Date value) {
			addCriterion("update_date =", value, "update_date");
			return (Criteria) this;
		}

		public Criteria andUpdate_dateNotEqualTo(Date value) {
			addCriterion("update_date <>", value, "update_date");
			return (Criteria) this;
		}

		public Criteria andUpdate_dateGreaterThan(Date value) {
			addCriterion("update_date >", value, "update_date");
			return (Criteria) this;
		}

		public Criteria andUpdate_dateGreaterThanOrEqualTo(Date value) {
			addCriterion("update_date >=", value, "update_date");
			return (Criteria) this;
		}

		public Criteria andUpdate_dateLessThan(Date value) {
			addCriterion("update_date <", value, "update_date");
			return (Criteria) this;
		}

		public Criteria andUpdate_dateLessThanOrEqualTo(Date value) {
			addCriterion("update_date <=", value, "update_date");
			return (Criteria) this;
		}

		public Criteria andUpdate_dateIn(List<Date> values) {
			addCriterion("update_date in", values, "update_date");
			return (Criteria) this;
		}

		public Criteria andUpdate_dateNotIn(List<Date> values) {
			addCriterion("update_date not in", values, "update_date");
			return (Criteria) this;
		}

		public Criteria andUpdate_dateBetween(Date value1, Date value2) {
			addCriterion("update_date between", value1, value2, "update_date");
			return (Criteria) this;
		}

		public Criteria andUpdate_dateNotBetween(Date value1, Date value2) {
			addCriterion("update_date not between", value1, value2,
					"update_date");
			return (Criteria) this;
		}

		public Criteria andBirthdayIsNull() {
			addCriterion("birthday is null");
			return (Criteria) this;
		}

		public Criteria andBirthdayIsNotNull() {
			addCriterion("birthday is not null");
			return (Criteria) this;
		}

		public Criteria andBirthdayEqualTo(String value) {
			addCriterion("birthday =", value, "birthday");
			return (Criteria) this;
		}

		public Criteria andBirthdayNotEqualTo(String value) {
			addCriterion("birthday <>", value, "birthday");
			return (Criteria) this;
		}

		public Criteria andBirthdayGreaterThan(String value) {
			addCriterion("birthday >", value, "birthday");
			return (Criteria) this;
		}

		public Criteria andBirthdayGreaterThanOrEqualTo(String value) {
			addCriterion("birthday >=", value, "birthday");
			return (Criteria) this;
		}

		public Criteria andBirthdayLessThan(String value) {
			addCriterion("birthday <", value, "birthday");
			return (Criteria) this;
		}

		public Criteria andBirthdayLessThanOrEqualTo(String value) {
			addCriterion("birthday <=", value, "birthday");
			return (Criteria) this;
		}

		public Criteria andBirthdayLike(String value) {
			addCriterion("birthday like", value, "birthday");
			return (Criteria) this;
		}

		public Criteria andBirthdayNotLike(String value) {
			addCriterion("birthday not like", value, "birthday");
			return (Criteria) this;
		}

		public Criteria andBirthdayIn(List<String> values) {
			addCriterion("birthday in", values, "birthday");
			return (Criteria) this;
		}

		public Criteria andBirthdayNotIn(List<String> values) {
			addCriterion("birthday not in", values, "birthday");
			return (Criteria) this;
		}

		public Criteria andBirthdayBetween(String value1, String value2) {
			addCriterion("birthday between", value1, value2, "birthday");
			return (Criteria) this;
		}

		public Criteria andBirthdayNotBetween(String value1, String value2) {
			addCriterion("birthday not between", value1, value2, "birthday");
			return (Criteria) this;
		}

		public Criteria andEthnic_group_idIsNull() {
			addCriterion("ethnic_group_id is null");
			return (Criteria) this;
		}

		public Criteria andEthnic_group_idIsNotNull() {
			addCriterion("ethnic_group_id is not null");
			return (Criteria) this;
		}

		public Criteria andEthnic_group_idEqualTo(Integer value) {
			addCriterion("ethnic_group_id =", value, "ethnic_group_id");
			return (Criteria) this;
		}

		public Criteria andEthnic_group_idNotEqualTo(Integer value) {
			addCriterion("ethnic_group_id <>", value, "ethnic_group_id");
			return (Criteria) this;
		}

		public Criteria andEthnic_group_idGreaterThan(Integer value) {
			addCriterion("ethnic_group_id >", value, "ethnic_group_id");
			return (Criteria) this;
		}

		public Criteria andEthnic_group_idGreaterThanOrEqualTo(Integer value) {
			addCriterion("ethnic_group_id >=", value, "ethnic_group_id");
			return (Criteria) this;
		}

		public Criteria andEthnic_group_idLessThan(Integer value) {
			addCriterion("ethnic_group_id <", value, "ethnic_group_id");
			return (Criteria) this;
		}

		public Criteria andEthnic_group_idLessThanOrEqualTo(Integer value) {
			addCriterion("ethnic_group_id <=", value, "ethnic_group_id");
			return (Criteria) this;
		}

		public Criteria andEthnic_group_idIn(List<Integer> values) {
			addCriterion("ethnic_group_id in", values, "ethnic_group_id");
			return (Criteria) this;
		}

		public Criteria andEthnic_group_idNotIn(List<Integer> values) {
			addCriterion("ethnic_group_id not in", values, "ethnic_group_id");
			return (Criteria) this;
		}

		public Criteria andEthnic_group_idBetween(Integer value1, Integer value2) {
			addCriterion("ethnic_group_id between", value1, value2,
					"ethnic_group_id");
			return (Criteria) this;
		}

		public Criteria andEthnic_group_idNotBetween(Integer value1,
				Integer value2) {
			addCriterion("ethnic_group_id not between", value1, value2,
					"ethnic_group_id");
			return (Criteria) this;
		}

		public Criteria andPolitical_status_idIsNull() {
			addCriterion("political_status_id is null");
			return (Criteria) this;
		}

		public Criteria andPolitical_status_idIsNotNull() {
			addCriterion("political_status_id is not null");
			return (Criteria) this;
		}

		public Criteria andPolitical_status_idEqualTo(Integer value) {
			addCriterion("political_status_id =", value, "political_status_id");
			return (Criteria) this;
		}

		public Criteria andPolitical_status_idNotEqualTo(Integer value) {
			addCriterion("political_status_id <>", value, "political_status_id");
			return (Criteria) this;
		}

		public Criteria andPolitical_status_idGreaterThan(Integer value) {
			addCriterion("political_status_id >", value, "political_status_id");
			return (Criteria) this;
		}

		public Criteria andPolitical_status_idGreaterThanOrEqualTo(Integer value) {
			addCriterion("political_status_id >=", value, "political_status_id");
			return (Criteria) this;
		}

		public Criteria andPolitical_status_idLessThan(Integer value) {
			addCriterion("political_status_id <", value, "political_status_id");
			return (Criteria) this;
		}

		public Criteria andPolitical_status_idLessThanOrEqualTo(Integer value) {
			addCriterion("political_status_id <=", value, "political_status_id");
			return (Criteria) this;
		}

		public Criteria andPolitical_status_idIn(List<Integer> values) {
			addCriterion("political_status_id in", values,
					"political_status_id");
			return (Criteria) this;
		}

		public Criteria andPolitical_status_idNotIn(List<Integer> values) {
			addCriterion("political_status_id not in", values,
					"political_status_id");
			return (Criteria) this;
		}

		public Criteria andPolitical_status_idBetween(Integer value1,
				Integer value2) {
			addCriterion("political_status_id between", value1, value2,
					"political_status_id");
			return (Criteria) this;
		}

		public Criteria andPolitical_status_idNotBetween(Integer value1,
				Integer value2) {
			addCriterion("political_status_id not between", value1, value2,
					"political_status_id");
			return (Criteria) this;
		}

		public Criteria andEmployerIsNull() {
			addCriterion("employer is null");
			return (Criteria) this;
		}

		public Criteria andEmployerIsNotNull() {
			addCriterion("employer is not null");
			return (Criteria) this;
		}

		public Criteria andEmployerEqualTo(String value) {
			addCriterion("employer =", value, "employer");
			return (Criteria) this;
		}

		public Criteria andEmployerNotEqualTo(String value) {
			addCriterion("employer <>", value, "employer");
			return (Criteria) this;
		}

		public Criteria andEmployerGreaterThan(String value) {
			addCriterion("employer >", value, "employer");
			return (Criteria) this;
		}

		public Criteria andEmployerGreaterThanOrEqualTo(String value) {
			addCriterion("employer >=", value, "employer");
			return (Criteria) this;
		}

		public Criteria andEmployerLessThan(String value) {
			addCriterion("employer <", value, "employer");
			return (Criteria) this;
		}

		public Criteria andEmployerLessThanOrEqualTo(String value) {
			addCriterion("employer <=", value, "employer");
			return (Criteria) this;
		}

		public Criteria andEmployerLike(String value) {
			addCriterion("employer like", value, "employer");
			return (Criteria) this;
		}

		public Criteria andEmployerNotLike(String value) {
			addCriterion("employer not like", value, "employer");
			return (Criteria) this;
		}

		public Criteria andEmployerIn(List<String> values) {
			addCriterion("employer in", values, "employer");
			return (Criteria) this;
		}

		public Criteria andEmployerNotIn(List<String> values) {
			addCriterion("employer not in", values, "employer");
			return (Criteria) this;
		}

		public Criteria andEmployerBetween(String value1, String value2) {
			addCriterion("employer between", value1, value2, "employer");
			return (Criteria) this;
		}

		public Criteria andEmployerNotBetween(String value1, String value2) {
			addCriterion("employer not between", value1, value2, "employer");
			return (Criteria) this;
		}

		public Criteria andGraduate_college_idIsNull() {
			addCriterion("graduate_college_id is null");
			return (Criteria) this;
		}

		public Criteria andGraduate_college_idIsNotNull() {
			addCriterion("graduate_college_id is not null");
			return (Criteria) this;
		}

		public Criteria andGraduate_college_idEqualTo(Integer value) {
			addCriterion("graduate_college_id =", value, "graduate_college_id");
			return (Criteria) this;
		}

		public Criteria andGraduate_college_idNotEqualTo(Integer value) {
			addCriterion("graduate_college_id <>", value, "graduate_college_id");
			return (Criteria) this;
		}

		public Criteria andGraduate_college_idGreaterThan(Integer value) {
			addCriterion("graduate_college_id >", value, "graduate_college_id");
			return (Criteria) this;
		}

		public Criteria andGraduate_college_idGreaterThanOrEqualTo(Integer value) {
			addCriterion("graduate_college_id >=", value, "graduate_college_id");
			return (Criteria) this;
		}

		public Criteria andGraduate_college_idLessThan(Integer value) {
			addCriterion("graduate_college_id <", value, "graduate_college_id");
			return (Criteria) this;
		}

		public Criteria andGraduate_college_idLessThanOrEqualTo(Integer value) {
			addCriterion("graduate_college_id <=", value, "graduate_college_id");
			return (Criteria) this;
		}

		public Criteria andGraduate_college_idIn(List<Integer> values) {
			addCriterion("graduate_college_id in", values,
					"graduate_college_id");
			return (Criteria) this;
		}

		public Criteria andGraduate_college_idNotIn(List<Integer> values) {
			addCriterion("graduate_college_id not in", values,
					"graduate_college_id");
			return (Criteria) this;
		}

		public Criteria andGraduate_college_idBetween(Integer value1,
				Integer value2) {
			addCriterion("graduate_college_id between", value1, value2,
					"graduate_college_id");
			return (Criteria) this;
		}

		public Criteria andGraduate_college_idNotBetween(Integer value1,
				Integer value2) {
			addCriterion("graduate_college_id not between", value1, value2,
					"graduate_college_id");
			return (Criteria) this;
		}

		public Criteria andGraduate_dateIsNull() {
			addCriterion("graduate_date is null");
			return (Criteria) this;
		}

		public Criteria andGraduate_dateIsNotNull() {
			addCriterion("graduate_date is not null");
			return (Criteria) this;
		}

		public Criteria andGraduate_dateEqualTo(String value) {
			addCriterion("graduate_date =", value, "graduate_date");
			return (Criteria) this;
		}

		public Criteria andGraduate_dateNotEqualTo(String value) {
			addCriterion("graduate_date <>", value, "graduate_date");
			return (Criteria) this;
		}

		public Criteria andGraduate_dateGreaterThan(String value) {
			addCriterion("graduate_date >", value, "graduate_date");
			return (Criteria) this;
		}

		public Criteria andGraduate_dateGreaterThanOrEqualTo(String value) {
			addCriterion("graduate_date >=", value, "graduate_date");
			return (Criteria) this;
		}

		public Criteria andGraduate_dateLessThan(String value) {
			addCriterion("graduate_date <", value, "graduate_date");
			return (Criteria) this;
		}

		public Criteria andGraduate_dateLessThanOrEqualTo(String value) {
			addCriterion("graduate_date <=", value, "graduate_date");
			return (Criteria) this;
		}

		public Criteria andGraduate_dateLike(String value) {
			addCriterion("graduate_date like", value, "graduate_date");
			return (Criteria) this;
		}

		public Criteria andGraduate_dateNotLike(String value) {
			addCriterion("graduate_date not like", value, "graduate_date");
			return (Criteria) this;
		}

		public Criteria andGraduate_dateIn(List<String> values) {
			addCriterion("graduate_date in", values, "graduate_date");
			return (Criteria) this;
		}

		public Criteria andGraduate_dateNotIn(List<String> values) {
			addCriterion("graduate_date not in", values, "graduate_date");
			return (Criteria) this;
		}

		public Criteria andGraduate_dateBetween(String value1, String value2) {
			addCriterion("graduate_date between", value1, value2,
					"graduate_date");
			return (Criteria) this;
		}

		public Criteria andGraduate_dateNotBetween(String value1, String value2) {
			addCriterion("graduate_date not between", value1, value2,
					"graduate_date");
			return (Criteria) this;
		}

		public Criteria andGraduate_certificate_numberIsNull() {
			addCriterion("graduate_certificate_number is null");
			return (Criteria) this;
		}

		public Criteria andGraduate_certificate_numberIsNotNull() {
			addCriterion("graduate_certificate_number is not null");
			return (Criteria) this;
		}

		public Criteria andGraduate_certificate_numberEqualTo(String value) {
			addCriterion("graduate_certificate_number =", value,
					"graduate_certificate_number");
			return (Criteria) this;
		}

		public Criteria andGraduate_certificate_numberNotEqualTo(String value) {
			addCriterion("graduate_certificate_number <>", value,
					"graduate_certificate_number");
			return (Criteria) this;
		}

		public Criteria andGraduate_certificate_numberGreaterThan(String value) {
			addCriterion("graduate_certificate_number >", value,
					"graduate_certificate_number");
			return (Criteria) this;
		}

		public Criteria andGraduate_certificate_numberGreaterThanOrEqualTo(
				String value) {
			addCriterion("graduate_certificate_number >=", value,
					"graduate_certificate_number");
			return (Criteria) this;
		}

		public Criteria andGraduate_certificate_numberLessThan(String value) {
			addCriterion("graduate_certificate_number <", value,
					"graduate_certificate_number");
			return (Criteria) this;
		}

		public Criteria andGraduate_certificate_numberLessThanOrEqualTo(
				String value) {
			addCriterion("graduate_certificate_number <=", value,
					"graduate_certificate_number");
			return (Criteria) this;
		}

		public Criteria andGraduate_certificate_numberLike(String value) {
			addCriterion("graduate_certificate_number like", value,
					"graduate_certificate_number");
			return (Criteria) this;
		}

		public Criteria andGraduate_certificate_numberNotLike(String value) {
			addCriterion("graduate_certificate_number not like", value,
					"graduate_certificate_number");
			return (Criteria) this;
		}

		public Criteria andGraduate_certificate_numberIn(List<String> values) {
			addCriterion("graduate_certificate_number in", values,
					"graduate_certificate_number");
			return (Criteria) this;
		}

		public Criteria andGraduate_certificate_numberNotIn(List<String> values) {
			addCriterion("graduate_certificate_number not in", values,
					"graduate_certificate_number");
			return (Criteria) this;
		}

		public Criteria andGraduate_certificate_numberBetween(String value1,
				String value2) {
			addCriterion("graduate_certificate_number between", value1, value2,
					"graduate_certificate_number");
			return (Criteria) this;
		}

		public Criteria andGraduate_certificate_numberNotBetween(String value1,
				String value2) {
			addCriterion("graduate_certificate_number not between", value1,
					value2, "graduate_certificate_number");
			return (Criteria) this;
		}

		public Criteria andPostal_codeIsNull() {
			addCriterion("postal_code is null");
			return (Criteria) this;
		}

		public Criteria andPostal_codeIsNotNull() {
			addCriterion("postal_code is not null");
			return (Criteria) this;
		}

		public Criteria andPostal_codeEqualTo(String value) {
			addCriterion("postal_code =", value, "postal_code");
			return (Criteria) this;
		}

		public Criteria andPostal_codeNotEqualTo(String value) {
			addCriterion("postal_code <>", value, "postal_code");
			return (Criteria) this;
		}

		public Criteria andPostal_codeGreaterThan(String value) {
			addCriterion("postal_code >", value, "postal_code");
			return (Criteria) this;
		}

		public Criteria andPostal_codeGreaterThanOrEqualTo(String value) {
			addCriterion("postal_code >=", value, "postal_code");
			return (Criteria) this;
		}

		public Criteria andPostal_codeLessThan(String value) {
			addCriterion("postal_code <", value, "postal_code");
			return (Criteria) this;
		}

		public Criteria andPostal_codeLessThanOrEqualTo(String value) {
			addCriterion("postal_code <=", value, "postal_code");
			return (Criteria) this;
		}

		public Criteria andPostal_codeLike(String value) {
			addCriterion("postal_code like", value, "postal_code");
			return (Criteria) this;
		}

		public Criteria andPostal_codeNotLike(String value) {
			addCriterion("postal_code not like", value, "postal_code");
			return (Criteria) this;
		}

		public Criteria andPostal_codeIn(List<String> values) {
			addCriterion("postal_code in", values, "postal_code");
			return (Criteria) this;
		}

		public Criteria andPostal_codeNotIn(List<String> values) {
			addCriterion("postal_code not in", values, "postal_code");
			return (Criteria) this;
		}

		public Criteria andPostal_codeBetween(String value1, String value2) {
			addCriterion("postal_code between", value1, value2, "postal_code");
			return (Criteria) this;
		}

		public Criteria andPostal_codeNotBetween(String value1, String value2) {
			addCriterion("postal_code not between", value1, value2,
					"postal_code");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table edu.student_info
	 * @mbggenerated  Thu Feb 09 18:11:26 CST 2012
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table edu.student_info
     *
     * @mbggenerated do_not_delete_during_merge Sun Jan 15 18:52:28 CST 2012
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}