package com.brightedu.model.edu;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class StudentChangeExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table edu.student_change
	 * @mbggenerated  Mon Jan 16 17:46:15 CST 2012
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table edu.student_change
	 * @mbggenerated  Mon Jan 16 17:46:15 CST 2012
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table edu.student_change
	 * @mbggenerated  Mon Jan 16 17:46:15 CST 2012
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table edu.student_change
	 * @mbggenerated  Mon Jan 16 17:46:15 CST 2012
	 */
	public StudentChangeExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table edu.student_change
	 * @mbggenerated  Mon Jan 16 17:46:15 CST 2012
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table edu.student_change
	 * @mbggenerated  Mon Jan 16 17:46:15 CST 2012
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table edu.student_change
	 * @mbggenerated  Mon Jan 16 17:46:15 CST 2012
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table edu.student_change
	 * @mbggenerated  Mon Jan 16 17:46:15 CST 2012
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table edu.student_change
	 * @mbggenerated  Mon Jan 16 17:46:15 CST 2012
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table edu.student_change
	 * @mbggenerated  Mon Jan 16 17:46:15 CST 2012
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table edu.student_change
	 * @mbggenerated  Mon Jan 16 17:46:15 CST 2012
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table edu.student_change
	 * @mbggenerated  Mon Jan 16 17:46:15 CST 2012
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table edu.student_change
	 * @mbggenerated  Mon Jan 16 17:46:15 CST 2012
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table edu.student_change
	 * @mbggenerated  Mon Jan 16 17:46:15 CST 2012
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table edu.student_change
	 * @mbggenerated  Mon Jan 16 17:46:15 CST 2012
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andChange_idIsNull() {
			addCriterion("change_id is null");
			return (Criteria) this;
		}

		public Criteria andChange_idIsNotNull() {
			addCriterion("change_id is not null");
			return (Criteria) this;
		}

		public Criteria andChange_idEqualTo(Integer value) {
			addCriterion("change_id =", value, "change_id");
			return (Criteria) this;
		}

		public Criteria andChange_idNotEqualTo(Integer value) {
			addCriterion("change_id <>", value, "change_id");
			return (Criteria) this;
		}

		public Criteria andChange_idGreaterThan(Integer value) {
			addCriterion("change_id >", value, "change_id");
			return (Criteria) this;
		}

		public Criteria andChange_idGreaterThanOrEqualTo(Integer value) {
			addCriterion("change_id >=", value, "change_id");
			return (Criteria) this;
		}

		public Criteria andChange_idLessThan(Integer value) {
			addCriterion("change_id <", value, "change_id");
			return (Criteria) this;
		}

		public Criteria andChange_idLessThanOrEqualTo(Integer value) {
			addCriterion("change_id <=", value, "change_id");
			return (Criteria) this;
		}

		public Criteria andChange_idIn(List<Integer> values) {
			addCriterion("change_id in", values, "change_id");
			return (Criteria) this;
		}

		public Criteria andChange_idNotIn(List<Integer> values) {
			addCriterion("change_id not in", values, "change_id");
			return (Criteria) this;
		}

		public Criteria andChange_idBetween(Integer value1, Integer value2) {
			addCriterion("change_id between", value1, value2, "change_id");
			return (Criteria) this;
		}

		public Criteria andChange_idNotBetween(Integer value1, Integer value2) {
			addCriterion("change_id not between", value1, value2, "change_id");
			return (Criteria) this;
		}

		public Criteria andStudent_idIsNull() {
			addCriterion("student_id is null");
			return (Criteria) this;
		}

		public Criteria andStudent_idIsNotNull() {
			addCriterion("student_id is not null");
			return (Criteria) this;
		}

		public Criteria andStudent_idEqualTo(Integer value) {
			addCriterion("student_id =", value, "student_id");
			return (Criteria) this;
		}

		public Criteria andStudent_idNotEqualTo(Integer value) {
			addCriterion("student_id <>", value, "student_id");
			return (Criteria) this;
		}

		public Criteria andStudent_idGreaterThan(Integer value) {
			addCriterion("student_id >", value, "student_id");
			return (Criteria) this;
		}

		public Criteria andStudent_idGreaterThanOrEqualTo(Integer value) {
			addCriterion("student_id >=", value, "student_id");
			return (Criteria) this;
		}

		public Criteria andStudent_idLessThan(Integer value) {
			addCriterion("student_id <", value, "student_id");
			return (Criteria) this;
		}

		public Criteria andStudent_idLessThanOrEqualTo(Integer value) {
			addCriterion("student_id <=", value, "student_id");
			return (Criteria) this;
		}

		public Criteria andStudent_idIn(List<Integer> values) {
			addCriterion("student_id in", values, "student_id");
			return (Criteria) this;
		}

		public Criteria andStudent_idNotIn(List<Integer> values) {
			addCriterion("student_id not in", values, "student_id");
			return (Criteria) this;
		}

		public Criteria andStudent_idBetween(Integer value1, Integer value2) {
			addCriterion("student_id between", value1, value2, "student_id");
			return (Criteria) this;
		}

		public Criteria andStudent_idNotBetween(Integer value1, Integer value2) {
			addCriterion("student_id not between", value1, value2, "student_id");
			return (Criteria) this;
		}

		public Criteria andChange_contentIsNull() {
			addCriterion("change_content is null");
			return (Criteria) this;
		}

		public Criteria andChange_contentIsNotNull() {
			addCriterion("change_content is not null");
			return (Criteria) this;
		}

		public Criteria andChange_contentEqualTo(String value) {
			addCriterion("change_content =", value, "change_content");
			return (Criteria) this;
		}

		public Criteria andChange_contentNotEqualTo(String value) {
			addCriterion("change_content <>", value, "change_content");
			return (Criteria) this;
		}

		public Criteria andChange_contentGreaterThan(String value) {
			addCriterion("change_content >", value, "change_content");
			return (Criteria) this;
		}

		public Criteria andChange_contentGreaterThanOrEqualTo(String value) {
			addCriterion("change_content >=", value, "change_content");
			return (Criteria) this;
		}

		public Criteria andChange_contentLessThan(String value) {
			addCriterion("change_content <", value, "change_content");
			return (Criteria) this;
		}

		public Criteria andChange_contentLessThanOrEqualTo(String value) {
			addCriterion("change_content <=", value, "change_content");
			return (Criteria) this;
		}

		public Criteria andChange_contentLike(String value) {
			addCriterion("change_content like", value, "change_content");
			return (Criteria) this;
		}

		public Criteria andChange_contentNotLike(String value) {
			addCriterion("change_content not like", value, "change_content");
			return (Criteria) this;
		}

		public Criteria andChange_contentIn(List<String> values) {
			addCriterion("change_content in", values, "change_content");
			return (Criteria) this;
		}

		public Criteria andChange_contentNotIn(List<String> values) {
			addCriterion("change_content not in", values, "change_content");
			return (Criteria) this;
		}

		public Criteria andChange_contentBetween(String value1, String value2) {
			addCriterion("change_content between", value1, value2,
					"change_content");
			return (Criteria) this;
		}

		public Criteria andChange_contentNotBetween(String value1, String value2) {
			addCriterion("change_content not between", value1, value2,
					"change_content");
			return (Criteria) this;
		}

		public Criteria andRegister_dateIsNull() {
			addCriterion("register_date is null");
			return (Criteria) this;
		}

		public Criteria andRegister_dateIsNotNull() {
			addCriterion("register_date is not null");
			return (Criteria) this;
		}

		public Criteria andRegister_dateEqualTo(Date value) {
			addCriterion("register_date =", value, "register_date");
			return (Criteria) this;
		}

		public Criteria andRegister_dateNotEqualTo(Date value) {
			addCriterion("register_date <>", value, "register_date");
			return (Criteria) this;
		}

		public Criteria andRegister_dateGreaterThan(Date value) {
			addCriterion("register_date >", value, "register_date");
			return (Criteria) this;
		}

		public Criteria andRegister_dateGreaterThanOrEqualTo(Date value) {
			addCriterion("register_date >=", value, "register_date");
			return (Criteria) this;
		}

		public Criteria andRegister_dateLessThan(Date value) {
			addCriterion("register_date <", value, "register_date");
			return (Criteria) this;
		}

		public Criteria andRegister_dateLessThanOrEqualTo(Date value) {
			addCriterion("register_date <=", value, "register_date");
			return (Criteria) this;
		}

		public Criteria andRegister_dateIn(List<Date> values) {
			addCriterion("register_date in", values, "register_date");
			return (Criteria) this;
		}

		public Criteria andRegister_dateNotIn(List<Date> values) {
			addCriterion("register_date not in", values, "register_date");
			return (Criteria) this;
		}

		public Criteria andRegister_dateBetween(Date value1, Date value2) {
			addCriterion("register_date between", value1, value2,
					"register_date");
			return (Criteria) this;
		}

		public Criteria andRegister_dateNotBetween(Date value1, Date value2) {
			addCriterion("register_date not between", value1, value2,
					"register_date");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table edu.student_change
	 * @mbggenerated  Mon Jan 16 17:46:15 CST 2012
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table edu.student_change
     *
     * @mbggenerated do_not_delete_during_merge Sun Jan 15 18:52:28 CST 2012
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}