package com.brightedu.model.edu;

import java.util.Date;

public class StudentClassified {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column edu.student_classified.classified_id
	 * @mbggenerated  Mon Jan 16 17:46:15 CST 2012
	 */
	private Integer classified_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column edu.student_classified.classified_name
	 * @mbggenerated  Mon Jan 16 17:46:15 CST 2012
	 */
	private String classified_name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column edu.student_classified.register_date
	 * @mbggenerated  Mon Jan 16 17:46:15 CST 2012
	 */
	private Date register_date;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column edu.student_classified.classified_id
	 * @return  the value of edu.student_classified.classified_id
	 * @mbggenerated  Mon Jan 16 17:46:15 CST 2012
	 */
	public Integer getClassified_id() {
		return classified_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column edu.student_classified.classified_id
	 * @param classified_id  the value for edu.student_classified.classified_id
	 * @mbggenerated  Mon Jan 16 17:46:15 CST 2012
	 */
	public void setClassified_id(Integer classified_id) {
		this.classified_id = classified_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column edu.student_classified.classified_name
	 * @return  the value of edu.student_classified.classified_name
	 * @mbggenerated  Mon Jan 16 17:46:15 CST 2012
	 */
	public String getClassified_name() {
		return classified_name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column edu.student_classified.classified_name
	 * @param classified_name  the value for edu.student_classified.classified_name
	 * @mbggenerated  Mon Jan 16 17:46:15 CST 2012
	 */
	public void setClassified_name(String classified_name) {
		this.classified_name = classified_name == null ? null : classified_name
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column edu.student_classified.register_date
	 * @return  the value of edu.student_classified.register_date
	 * @mbggenerated  Mon Jan 16 17:46:15 CST 2012
	 */
	public Date getRegister_date() {
		return register_date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column edu.student_classified.register_date
	 * @param register_date  the value for edu.student_classified.register_date
	 * @mbggenerated  Mon Jan 16 17:46:15 CST 2012
	 */
	public void setRegister_date(Date register_date) {
		this.register_date = register_date;
	}
}