package com.brightedu.model.edu;

import java.io.Serializable;
import java.util.Date;

public class Subjects  implements Serializable{

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column edu.subjects.subject_id
	 * @mbggenerated  Thu Feb 09 18:11:26 CST 2012
	 */
	private Integer subject_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column edu.subjects.subject_name
	 * @mbggenerated  Thu Feb 09 18:11:26 CST 2012
	 */
	private String subject_name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column edu.subjects.register_date
	 * @mbggenerated  Thu Feb 09 18:11:26 CST 2012
	 */
	private Date register_date;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table edu.subjects
	 * @mbggenerated  Thu Feb 09 18:11:26 CST 2012
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column edu.subjects.subject_id
	 * @return  the value of edu.subjects.subject_id
	 * @mbggenerated  Thu Feb 09 18:11:26 CST 2012
	 */
	public Integer getSubject_id() {
		return subject_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column edu.subjects.subject_id
	 * @param subject_id  the value for edu.subjects.subject_id
	 * @mbggenerated  Thu Feb 09 18:11:26 CST 2012
	 */
	public void setSubject_id(Integer subject_id) {
		this.subject_id = subject_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column edu.subjects.subject_name
	 * @return  the value of edu.subjects.subject_name
	 * @mbggenerated  Thu Feb 09 18:11:26 CST 2012
	 */
	public String getSubject_name() {
		return subject_name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column edu.subjects.subject_name
	 * @param subject_name  the value for edu.subjects.subject_name
	 * @mbggenerated  Thu Feb 09 18:11:26 CST 2012
	 */
	public void setSubject_name(String subject_name) {
		this.subject_name = subject_name == null ? null : subject_name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column edu.subjects.register_date
	 * @return  the value of edu.subjects.register_date
	 * @mbggenerated  Thu Feb 09 18:11:26 CST 2012
	 */
	public Date getRegister_date() {
		return register_date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column edu.subjects.register_date
	 * @param register_date  the value for edu.subjects.register_date
	 * @mbggenerated  Thu Feb 09 18:11:26 CST 2012
	 */
	public void setRegister_date(Date register_date) {
		this.register_date = register_date;
	}
}